// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiclientgo

import (
	"github.com/gleanwork/api-client-go/internal/config"
	"github.com/gleanwork/api-client-go/internal/hooks"
)

type Data struct {
	Policies *Policies
	Reports  *Reports

	rootSDK          *Glean
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newData(rootSDK *Glean, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Data {
	return &Data{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Policies:         newPolicies(rootSDK, sdkConfig, hooks),
		Reports:          newReports(rootSDK, sdkConfig, hooks),
	}
}
