// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiclientgo

type Data struct {
	Policies *Policies
	Reports  *Reports

	sdkConfiguration sdkConfiguration
}

func newData(sdkConfig sdkConfiguration) *Data {
	return &Data{
		sdkConfiguration: sdkConfig,
		Policies:         newPolicies(sdkConfig),
		Reports:          newReports(sdkConfig),
	}
}
