// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiclientgo

import (
	"github.com/gleanwork/api-client-go/internal/config"
	"github.com/gleanwork/api-client-go/internal/hooks"
)

type Governance struct {
	Data      *Data
	Documents *GovernanceDocuments

	rootSDK          *Glean
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newGovernance(rootSDK *Glean, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Governance {
	return &Governance{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Data:             newData(rootSDK, sdkConfig, hooks),
		Documents:        newGovernanceDocuments(rootSDK, sdkConfig, hooks),
	}
}
