// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type CreateAndWaitRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	AgentRunWaitResponse *components.AgentRunWaitResponse
}

func (c *CreateAndWaitRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAndWaitRunResponse) GetAgentRunWaitResponse() *components.AgentRunWaitResponse {
	if c == nil {
		return nil
	}
	return c.AgentRunWaitResponse
}
