// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type CreateAndStreamRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Res *string
}

func (c *CreateAndStreamRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAndStreamRunResponse) GetRes() *string {
	if c == nil {
		return nil
	}
	return c.Res
}
