// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type DeletechatfilesRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset         *int64                            `queryParam:"style=form,explode=true,name=timezoneOffset"`
	DeleteChatFilesRequest components.DeleteChatFilesRequest `request:"mediaType=application/json"`
}

func (d *DeletechatfilesRequest) GetLocale() *string {
	if d == nil {
		return nil
	}
	return d.Locale
}

func (d *DeletechatfilesRequest) GetTimezoneOffset() *int64 {
	if d == nil {
		return nil
	}
	return d.TimezoneOffset
}

func (d *DeletechatfilesRequest) GetDeleteChatFilesRequest() components.DeleteChatFilesRequest {
	if d == nil {
		return components.DeleteChatFilesRequest{}
	}
	return d.DeleteChatFilesRequest
}

type DeletechatfilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeletechatfilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
