// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type DeleteannouncementRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// Delete announcement request
	DeleteAnnouncementRequest components.DeleteAnnouncementRequest `request:"mediaType=application/json"`
}

func (d *DeleteannouncementRequest) GetLocale() *string {
	if d == nil {
		return nil
	}
	return d.Locale
}

func (d *DeleteannouncementRequest) GetDeleteAnnouncementRequest() components.DeleteAnnouncementRequest {
	if d == nil {
		return components.DeleteAnnouncementRequest{}
	}
	return d.DeleteAnnouncementRequest
}

type DeleteannouncementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteannouncementResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
