// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type DeletechatsRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset     *int64                        `queryParam:"style=form,explode=true,name=timezoneOffset"`
	DeleteChatsRequest components.DeleteChatsRequest `request:"mediaType=application/json"`
}

func (d *DeletechatsRequest) GetLocale() *string {
	if d == nil {
		return nil
	}
	return d.Locale
}

func (d *DeletechatsRequest) GetTimezoneOffset() *int64 {
	if d == nil {
		return nil
	}
	return d.TimezoneOffset
}

func (d *DeletechatsRequest) GetDeleteChatsRequest() components.DeleteChatsRequest {
	if d == nil {
		return components.DeleteChatsRequest{}
	}
	return d.DeleteChatsRequest
}

type DeletechatsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeletechatsResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
