// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type EditanswerRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// EditAnswer request
	EditAnswerRequest components.EditAnswerRequest `request:"mediaType=application/json"`
}

func (e *EditanswerRequest) GetLocale() *string {
	if e == nil {
		return nil
	}
	return e.Locale
}

func (e *EditanswerRequest) GetEditAnswerRequest() components.EditAnswerRequest {
	if e == nil {
		return components.EditAnswerRequest{}
	}
	return e.EditAnswerRequest
}

type EditanswerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Answer *components.Answer
}

func (e *EditanswerResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EditanswerResponse) GetAnswer() *components.Answer {
	if e == nil {
		return nil
	}
	return e.Answer
}
