// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type GetAgentRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset *int64 `queryParam:"style=form,explode=true,name=timezoneOffset"`
	// The ID of the agent.
	AgentID string `pathParam:"style=simple,explode=false,name=agent_id"`
}

func (g *GetAgentRequest) GetLocale() *string {
	if g == nil {
		return nil
	}
	return g.Locale
}

func (g *GetAgentRequest) GetTimezoneOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.TimezoneOffset
}

func (g *GetAgentRequest) GetAgentID() string {
	if g == nil {
		return ""
	}
	return g.AgentID
}

type GetAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Agent *components.Agent
}

func (g *GetAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentResponse) GetAgent() *components.Agent {
	if g == nil {
		return nil
	}
	return g.Agent
}
