// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type GetanswerRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// GetAnswer request
	GetAnswerRequest components.GetAnswerRequest `request:"mediaType=application/json"`
}

func (g *GetanswerRequest) GetLocale() *string {
	if g == nil {
		return nil
	}
	return g.Locale
}

func (g *GetanswerRequest) GetGetAnswerRequest() components.GetAnswerRequest {
	if g == nil {
		return components.GetAnswerRequest{}
	}
	return g.GetAnswerRequest
}

type GetanswerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetAnswerResponse *components.GetAnswerResponse
}

func (g *GetanswerResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetanswerResponse) GetGetAnswerResponse() *components.GetAnswerResponse {
	if g == nil {
		return nil
	}
	return g.GetAnswerResponse
}
