// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type GetdocumentsbyfacetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetDocumentsByFacetsResponse *components.GetDocumentsByFacetsResponse
}

func (g *GetdocumentsbyfacetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetdocumentsbyfacetsResponse) GetGetDocumentsByFacetsResponse() *components.GetDocumentsByFacetsResponse {
	if g == nil {
		return nil
	}
	return g.GetDocumentsByFacetsResponse
}
