// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type GetpolicyRequest struct {
	// The id of the policy to fetch.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The version of the policy to fetch. Each time a policy is updated, the older version is still stored. If this is left empty, the latest policy is fetched.
	Version *int64 `queryParam:"style=form,explode=true,name=version"`
}

func (g *GetpolicyRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetpolicyRequest) GetVersion() *int64 {
	if g == nil {
		return nil
	}
	return g.Version
}

type GetpolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetDlpReportResponse *components.GetDlpReportResponse
}

func (g *GetpolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetpolicyResponse) GetGetDlpReportResponse() *components.GetDlpReportResponse {
	if g == nil {
		return nil
	}
	return g.GetDlpReportResponse
}
