// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type GetshortcutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetShortcutResponse *components.GetShortcutResponse
}

func (g *GetshortcutResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetshortcutResponse) GetGetShortcutResponse() *components.GetShortcutResponse {
	if g == nil {
		return nil
	}
	return g.GetShortcutResponse
}
