// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type ListentitiesRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// List people request
	ListEntitiesRequest components.ListEntitiesRequest `request:"mediaType=application/json"`
}

func (l *ListentitiesRequest) GetLocale() *string {
	if l == nil {
		return nil
	}
	return l.Locale
}

func (l *ListentitiesRequest) GetListEntitiesRequest() components.ListEntitiesRequest {
	if l == nil {
		return components.ListEntitiesRequest{}
	}
	return l.ListEntitiesRequest
}

type ListentitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListEntitiesResponse *components.ListEntitiesResponse
}

func (l *ListentitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListentitiesResponse) GetListEntitiesResponse() *components.ListEntitiesResponse {
	if l == nil {
		return nil
	}
	return l.ListEntitiesResponse
}
