// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

// ListpinsRequest - List pins request
type ListpinsRequest struct {
}

type ListpinsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListPinsResponse *components.ListPinsResponse
}

func (l *ListpinsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListpinsResponse) GetListPinsResponse() *components.ListPinsResponse {
	if l == nil {
		return nil
	}
	return l.ListPinsResponse
}
