// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type MessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MessagesResponse *components.MessagesResponse
}

func (m *MessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MessagesResponse) GetMessagesResponse() *components.MessagesResponse {
	if m == nil {
		return nil
	}
	return m.MessagesResponse
}
