// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PostAPIIndexV1RotatetokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RotateTokenResponse *components.RotateTokenResponse
}

func (p *PostAPIIndexV1RotatetokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAPIIndexV1RotatetokenResponse) GetRotateTokenResponse() *components.RotateTokenResponse {
	if p == nil {
		return nil
	}
	return p.RotateTokenResponse
}
