// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PostAPIIndexV1GetdocumentcountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetDocumentCountResponse *components.GetDocumentCountResponse
}

func (p *PostAPIIndexV1GetdocumentcountResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAPIIndexV1GetdocumentcountResponse) GetGetDocumentCountResponse() *components.GetDocumentCountResponse {
	if p == nil {
		return nil
	}
	return p.GetDocumentCountResponse
}
