// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PostAPIIndexV1GetdatasourceconfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CustomDatasourceConfig *components.CustomDatasourceConfig
}

func (p *PostAPIIndexV1GetdatasourceconfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAPIIndexV1GetdatasourceconfigResponse) GetCustomDatasourceConfig() *components.CustomDatasourceConfig {
	if p == nil {
		return nil
	}
	return p.CustomDatasourceConfig
}
