// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type RecommendationsRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// Recommendations request
	RecommendationsRequest components.RecommendationsRequest `request:"mediaType=application/json"`
}

func (r *RecommendationsRequest) GetLocale() *string {
	if r == nil {
		return nil
	}
	return r.Locale
}

func (r *RecommendationsRequest) GetRecommendationsRequest() components.RecommendationsRequest {
	if r == nil {
		return components.RecommendationsRequest{}
	}
	return r.RecommendationsRequest
}

type RecommendationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ResultsResponse *components.ResultsResponse
}

func (r *RecommendationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RecommendationsResponse) GetResultsResponse() *components.ResultsResponse {
	if r == nil {
		return nil
	}
	return r.ResultsResponse
}
