// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type SearchRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// Search request
	SearchRequest components.SearchRequest `request:"mediaType=application/json"`
}

func (s *SearchRequest) GetLocale() *string {
	if s == nil {
		return nil
	}
	return s.Locale
}

func (s *SearchRequest) GetSearchRequest() components.SearchRequest {
	if s == nil {
		return components.SearchRequest{}
	}
	return s.SearchRequest
}

type SearchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SearchResponse *components.SearchResponse
}

func (s *SearchResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SearchResponse) GetSearchResponse() *components.SearchResponse {
	if s == nil {
		return nil
	}
	return s.SearchResponse
}
