// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type SummarizeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SummarizeResponse *components.SummarizeResponse
}

func (s *SummarizeResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SummarizeResponse) GetSummarizeResponse() *components.SummarizeResponse {
	if s == nil {
		return nil
	}
	return s.SummarizeResponse
}
