// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type UnpinRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// Details about the pin being unpinned.
	Unpin components.Unpin `request:"mediaType=application/json"`
}

func (u *UnpinRequest) GetLocale() *string {
	if u == nil {
		return nil
	}
	return u.Locale
}

func (u *UnpinRequest) GetUnpin() components.Unpin {
	if u == nil {
		return components.Unpin{}
	}
	return u.Unpin
}

type UnpinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (u *UnpinResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}
