// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostRestAPIV1Createcollection(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "createcollection[0]":
			dir.HandlerFunc("createcollection", testCreatecollectionCreatecollection0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testCreatecollectionCreatecollection0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.CreatecollectionResponseBody = types.Pointer(operations.CreateCreatecollectionResponseBodyResponseBody2(
		operations.ResponseBody2{
			Collection: &components.Collection{
				Name:        "<value>",
				Description: "motionless whenever paintwork import over cuckoo",
				AddedRoles: []components.UserRoleSpecification{
					components.UserRoleSpecification{
						Person: &components.Person{
							Name:         "George Clooney",
							ObfuscatedID: "abc123",
						},
						Role: components.UserRoleOwner,
					},
				},
				RemovedRoles: []components.UserRoleSpecification{
					components.UserRoleSpecification{
						Person: &components.Person{
							Name:         "George Clooney",
							ObfuscatedID: "abc123",
						},
						Role: components.UserRoleViewer,
					},
				},
				AudienceFilters: []components.FacetFilter{
					components.FacetFilter{
						FieldName: types.String("type"),
						Values: []components.FacetFilterValue{
							components.FacetFilterValue{
								Value:        types.String("Spreadsheet"),
								RelationType: components.RelationTypeEquals.ToPointer(),
							},
							components.FacetFilterValue{
								Value:        types.String("Presentation"),
								RelationType: components.RelationTypeEquals.ToPointer(),
							},
						},
					},
				},
				ID: 363711,
				Creator: &components.Person{
					Name:         "George Clooney",
					ObfuscatedID: "abc123",
				},
				UpdatedBy: &components.Person{
					Name:         "George Clooney",
					ObfuscatedID: "abc123",
				},
				Items: []components.CollectionItem{
					components.CollectionItem{
						CollectionID: 570197,
						CreatedBy: &components.Person{
							Name:         "George Clooney",
							ObfuscatedID: "abc123",
						},
						Document: &components.Document{
							ContainerDocument: &components.Document{
								Metadata: &components.DocumentMetadata{
									Datasource: types.String("datasource"),
									ObjectType: types.String("Feature Request"),
									Container:  types.String("container"),
									ParentID:   types.String("JIRA_EN-1337"),
									MimeType:   types.String("mimeType"),
									DocumentID: types.String("documentId"),
									CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									Author: &components.Person{
										Name:         "name",
										ObfuscatedID: "<id>",
									},
									Components: []string{
										"Backend",
										"Networking",
									},
									Status: types.String("[\"Done\"]"),
									CustomData: map[string]components.CustomDataValue{
										"someCustomField": components.CustomDataValue{},
									},
								},
							},
							ParentDocument: &components.Document{
								Metadata: &components.DocumentMetadata{
									Datasource: types.String("datasource"),
									ObjectType: types.String("Feature Request"),
									Container:  types.String("container"),
									ParentID:   types.String("JIRA_EN-1337"),
									MimeType:   types.String("mimeType"),
									DocumentID: types.String("documentId"),
									CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									Author: &components.Person{
										Name:         "name",
										ObfuscatedID: "<id>",
									},
									Components: []string{
										"Backend",
										"Networking",
									},
									Status: types.String("[\"Done\"]"),
									CustomData: map[string]components.CustomDataValue{
										"someCustomField": components.CustomDataValue{},
									},
								},
							},
							Metadata: &components.DocumentMetadata{
								Datasource: types.String("datasource"),
								ObjectType: types.String("Feature Request"),
								Container:  types.String("container"),
								ParentID:   types.String("JIRA_EN-1337"),
								MimeType:   types.String("mimeType"),
								DocumentID: types.String("documentId"),
								CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
								UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
								Author: &components.Person{
									Name:         "name",
									ObfuscatedID: "<id>",
								},
								Components: []string{
									"Backend",
									"Networking",
								},
								Status: types.String("[\"Done\"]"),
								CustomData: map[string]components.CustomDataValue{
									"someCustomField": components.CustomDataValue{},
								},
							},
						},
						Shortcut: &components.Shortcut{
							InputAlias: "<value>",
							CreatedBy: &components.Person{
								Name:         "George Clooney",
								ObfuscatedID: "abc123",
							},
							UpdatedBy: &components.Person{
								Name:         "George Clooney",
								ObfuscatedID: "abc123",
							},
							DestinationDocument: &components.Document{
								ContainerDocument: &components.Document{
									Metadata: &components.DocumentMetadata{
										Datasource: types.String("datasource"),
										ObjectType: types.String("Feature Request"),
										Container:  types.String("container"),
										ParentID:   types.String("JIRA_EN-1337"),
										MimeType:   types.String("mimeType"),
										DocumentID: types.String("documentId"),
										CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
										UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
										Author: &components.Person{
											Name:         "name",
											ObfuscatedID: "<id>",
										},
										Components: []string{
											"Backend",
											"Networking",
										},
										Status: types.String("[\"Done\"]"),
										CustomData: map[string]components.CustomDataValue{
											"someCustomField": components.CustomDataValue{},
										},
									},
								},
								ParentDocument: &components.Document{
									Metadata: &components.DocumentMetadata{
										Datasource: types.String("datasource"),
										ObjectType: types.String("Feature Request"),
										Container:  types.String("container"),
										ParentID:   types.String("JIRA_EN-1337"),
										MimeType:   types.String("mimeType"),
										DocumentID: types.String("documentId"),
										CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
										UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
										Author: &components.Person{
											Name:         "name",
											ObfuscatedID: "<id>",
										},
										Components: []string{
											"Backend",
											"Networking",
										},
										Status: types.String("[\"Done\"]"),
										CustomData: map[string]components.CustomDataValue{
											"someCustomField": components.CustomDataValue{},
										},
									},
								},
								Metadata: &components.DocumentMetadata{
									Datasource: types.String("datasource"),
									ObjectType: types.String("Feature Request"),
									Container:  types.String("container"),
									ParentID:   types.String("JIRA_EN-1337"),
									MimeType:   types.String("mimeType"),
									DocumentID: types.String("documentId"),
									CreateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									UpdateTime: types.MustNewTimeFromString("2000-01-23T04:56:07.000Z"),
									Author: &components.Person{
										Name:         "name",
										ObfuscatedID: "<id>",
									},
									Components: []string{
										"Backend",
										"Networking",
									},
									Status: types.String("[\"Done\"]"),
									CustomData: map[string]components.CustomDataValue{
										"someCustomField": components.CustomDataValue{},
									},
								},
							},
							Roles: []components.UserRoleSpecification{
								components.UserRoleSpecification{
									Person: &components.Person{
										Name:         "George Clooney",
										ObfuscatedID: "abc123",
									},
									Role: components.UserRoleAnswerModerator,
								},
							},
						},
						Collection: &components.Collection{
							Name:        "<value>",
							Description: "athwart skateboard newsstand farm bourgeoisie ah how elliptical aha well-to-do",
							AudienceFilters: []components.FacetFilter{
								components.FacetFilter{
									FieldName: types.String("type"),
									Values: []components.FacetFilterValue{
										components.FacetFilterValue{
											Value:        types.String("Spreadsheet"),
											RelationType: components.RelationTypeEquals.ToPointer(),
										},
										components.FacetFilterValue{
											Value:        types.String("Presentation"),
											RelationType: components.RelationTypeEquals.ToPointer(),
										},
									},
								},
							},
							ID: 643990,
							Creator: &components.Person{
								Name:         "George Clooney",
								ObfuscatedID: "abc123",
							},
							UpdatedBy: &components.Person{
								Name:         "George Clooney",
								ObfuscatedID: "abc123",
							},
							Children: []components.Collection{
								components.Collection{
									Name:        "<value>",
									Description: "woot purse salty even as advanced",
									AudienceFilters: []components.FacetFilter{
										components.FacetFilter{
											FieldName: types.String("type"),
											Values: []components.FacetFilterValue{
												components.FacetFilterValue{
													Value:        types.String("Spreadsheet"),
													RelationType: components.RelationTypeEquals.ToPointer(),
												},
												components.FacetFilterValue{
													Value:        types.String("Presentation"),
													RelationType: components.RelationTypeEquals.ToPointer(),
												},
											},
										},
									},
									ID: 359978,
									Creator: &components.Person{
										Name:         "George Clooney",
										ObfuscatedID: "abc123",
									},
									UpdatedBy: &components.Person{
										Name:         "George Clooney",
										ObfuscatedID: "abc123",
									},
								},
							},
						},
						ItemType: components.CollectionItemItemTypeURL,
					},
				},
			},
			Error: components.CollectionError{
				ErrorCode: components.CollectionErrorErrorCodeNotFound,
			},
		},
	))
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
