// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"testing"
)

func TestClientUser_Addcredential(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step addcredential.test referencing operation addcredential not found in document`]")
}

func TestClientUser_Deletequeryhistory(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step deletequeryhistory.test referencing operation deletequeryhistory not found in document`]")
}

func TestClientUser_Invite(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step invite.test referencing operation invite not found in document`]")
}

func TestClientUser_Publicconfig(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step publicconfig.test referencing operation publicconfig not found in document`]")
}

func TestClientUser_Removecredential(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step removecredential.test referencing operation removecredential not found in document`]")
}

func TestClientUser_SupportEmail(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step support_email.test referencing operation support_email not found in document`]")
}
