// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

// ActivityEventAction - The type of activity this represents.
type ActivityEventAction string

const (
	// ActivityEventActionView Represents a visit to the given `url`.
	ActivityEventActionView ActivityEventAction = "VIEW"
	// ActivityEventActionEdit Represents an edit of the document represented by the `url`.
	ActivityEventActionEdit ActivityEventAction = "EDIT"
	// ActivityEventActionSearch Represents a search performed at the given `url`.
	ActivityEventActionSearch ActivityEventAction = "SEARCH"
	// ActivityEventActionComment Represents a comment on the document represented by the `url`.
	ActivityEventActionComment ActivityEventAction = "COMMENT"
	// ActivityEventActionCrawl Represents an explicit request to index the given `url` along with associated attributes in this payload.
	ActivityEventActionCrawl ActivityEventAction = "CRAWL"
	// ActivityEventActionHistoricalSearch Represents a search performed at the given `url` as indicated by the user's history.
	ActivityEventActionHistoricalSearch ActivityEventAction = "HISTORICAL_SEARCH"
	// ActivityEventActionHistoricalView Represents a visit to the given `url` as indicated by the user's history.
	ActivityEventActionHistoricalView ActivityEventAction = "HISTORICAL_VIEW"
)

func (e ActivityEventAction) ToPointer() *ActivityEventAction {
	return &e
}
func (e *ActivityEventAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "VIEW":
		fallthrough
	case "EDIT":
		fallthrough
	case "SEARCH":
		fallthrough
	case "COMMENT":
		fallthrough
	case "CRAWL":
		fallthrough
	case "HISTORICAL_SEARCH":
		fallthrough
	case "HISTORICAL_VIEW":
		*e = ActivityEventAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActivityEventAction: %v", v)
	}
}

type ActivityEvent struct {
	// Universally unique identifier of the event. To allow for reliable retransmission, only the earliest received event of a given UUID is considered valid by the server and subsequent are ignored.
	ID *string `json:"id,omitempty"`
	// The type of activity this represents.
	Action ActivityEventAction  `json:"action"`
	Params *ActivityEventParams `json:"params,omitempty"`
	// The ISO 8601 timestamp when the activity began.
	Timestamp time.Time `json:"timestamp"`
	// The URL of the activity.
	URL string `json:"url"`
}

func (a ActivityEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivityEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"action", "timestamp", "url"}); err != nil {
		return err
	}
	return nil
}

func (a *ActivityEvent) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *ActivityEvent) GetAction() ActivityEventAction {
	if a == nil {
		return ActivityEventAction("")
	}
	return a.Action
}

func (a *ActivityEvent) GetParams() *ActivityEventParams {
	if a == nil {
		return nil
	}
	return a.Params
}

func (a *ActivityEvent) GetTimestamp() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Timestamp
}

func (a *ActivityEvent) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}
