// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentsInsightsV2Response struct {
	// Number of current Monthly Active Users, in the specified departments.
	MonthlyActiveUsers *int64 `json:"monthlyActiveUsers,omitempty"`
	// Number of current Weekly Active Users, in the specified departments.
	WeeklyActiveUsers           *int64            `json:"weeklyActiveUsers,omitempty"`
	MonthlyActiveUserTimeseries *LabeledCountInfo `json:"monthlyActiveUserTimeseries,omitempty"`
	WeeklyActiveUserTimeseries  *LabeledCountInfo `json:"weeklyActiveUserTimeseries,omitempty"`
	DailyActiveUserTimeseries   *LabeledCountInfo `json:"dailyActiveUserTimeseries,omitempty"`
	// Total number of shared agents.
	SharedAgentsCount               *int64                           `json:"sharedAgentsCount,omitempty"`
	TopAgentsInsights               []PerAgentInsight                `json:"topAgentsInsights,omitempty"`
	AgentsUsageByDepartmentInsights []AgentsUsageByDepartmentInsight `json:"agentsUsageByDepartmentInsights,omitempty"`
	AgentUsersInsights              []AgentUsersInsight              `json:"agentUsersInsights,omitempty"`
	DailyAgentRunsTimeseries        *LabeledCountInfo                `json:"dailyAgentRunsTimeseries,omitempty"`
	UpvotesTimeseries               *LabeledCountInfo                `json:"upvotesTimeseries,omitempty"`
	DownvotesTimeseries             *LabeledCountInfo                `json:"downvotesTimeseries,omitempty"`
}

func (a *AgentsInsightsV2Response) GetMonthlyActiveUsers() *int64 {
	if a == nil {
		return nil
	}
	return a.MonthlyActiveUsers
}

func (a *AgentsInsightsV2Response) GetWeeklyActiveUsers() *int64 {
	if a == nil {
		return nil
	}
	return a.WeeklyActiveUsers
}

func (a *AgentsInsightsV2Response) GetMonthlyActiveUserTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.MonthlyActiveUserTimeseries
}

func (a *AgentsInsightsV2Response) GetWeeklyActiveUserTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.WeeklyActiveUserTimeseries
}

func (a *AgentsInsightsV2Response) GetDailyActiveUserTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.DailyActiveUserTimeseries
}

func (a *AgentsInsightsV2Response) GetSharedAgentsCount() *int64 {
	if a == nil {
		return nil
	}
	return a.SharedAgentsCount
}

func (a *AgentsInsightsV2Response) GetTopAgentsInsights() []PerAgentInsight {
	if a == nil {
		return nil
	}
	return a.TopAgentsInsights
}

func (a *AgentsInsightsV2Response) GetAgentsUsageByDepartmentInsights() []AgentsUsageByDepartmentInsight {
	if a == nil {
		return nil
	}
	return a.AgentsUsageByDepartmentInsights
}

func (a *AgentsInsightsV2Response) GetAgentUsersInsights() []AgentUsersInsight {
	if a == nil {
		return nil
	}
	return a.AgentUsersInsights
}

func (a *AgentsInsightsV2Response) GetDailyAgentRunsTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.DailyAgentRunsTimeseries
}

func (a *AgentsInsightsV2Response) GetUpvotesTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.UpvotesTimeseries
}

func (a *AgentsInsightsV2Response) GetDownvotesTimeseries() *LabeledCountInfo {
	if a == nil {
		return nil
	}
	return a.DownvotesTimeseries
}
