// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentRunCreate - Payload for creating a run.
type AgentRunCreate struct {
	// The ID of the agent to run.
	AgentID string `json:"agent_id"`
	// The input to the agent.
	Input map[string]any `json:"input,omitempty"`
	// The messages to pass an input to the agent.
	Messages []Message `json:"messages,omitempty"`
	// The metadata to pass to the agent.
	Metadata map[string]any `json:"metadata,omitempty"`
}

func (a *AgentRunCreate) GetAgentID() string {
	if a == nil {
		return ""
	}
	return a.AgentID
}

func (a *AgentRunCreate) GetInput() map[string]any {
	if a == nil {
		return nil
	}
	return a.Input
}

func (a *AgentRunCreate) GetMessages() []Message {
	if a == nil {
		return nil
	}
	return a.Messages
}

func (a *AgentRunCreate) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}
