// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentEnum - Name of the agent.
type AgentEnum string

const (
	// AgentEnumDefault Integrates with your company's knowledge. This will soon be deprecated in favor of the FAST and ADVANCED `agent` values
	AgentEnumDefault AgentEnum = "DEFAULT"
	// AgentEnumGpt Communicates directly with the LLM. This will soon be deprecated in favor of the FAST and ADVANCED `agent` values
	AgentEnumGpt AgentEnum = "GPT"
	// AgentEnumUniversal Uses both company and web knowledge. This will soon be deprecated in favor of the FAST and ADVANCED `agent` values
	AgentEnumUniversal AgentEnum = "UNIVERSAL"
	// AgentEnumFast Uses an agent powered by the agentic engine that responds faster but may have lower quality results. Requires the agentic engine to be enabled in the deployment.
	AgentEnumFast AgentEnum = "FAST"
	// AgentEnumAdvanced Uses an agent powered by the agentic engine that thinks for longer and potentially makes more LLM calls to return higher quality results. Requires the agentic engine to be enabled in the deployment.
	AgentEnumAdvanced AgentEnum = "ADVANCED"
	// AgentEnumAuto Uses an agent powered by the agentic engine that routes between reasoning efforts based on the question and context.
	AgentEnumAuto AgentEnum = "AUTO"
)

func (e AgentEnum) ToPointer() *AgentEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "DEFAULT", "GPT", "UNIVERSAL", "FAST", "ADVANCED", "AUTO":
			return true
		}
	}
	return false
}

// Mode - Top level modes to run GleanChat in.
type Mode string

const (
	// ModeDefault Used if no mode supplied.
	ModeDefault Mode = "DEFAULT"
	// ModeQuick Deprecated.
	ModeQuick Mode = "QUICK"
)

func (e Mode) ToPointer() *Mode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Mode) IsExact() bool {
	if e != nil {
		switch *e {
		case "DEFAULT", "QUICK":
			return true
		}
	}
	return false
}

// AgentConfig - Describes the agent that executes the request.
type AgentConfig struct {
	// Name of the agent.
	Agent *AgentEnum `json:"agent,omitempty"`
	// The types of tools that the agent is allowed to use. Only works with FAST and ADVANCED `agent` values
	ToolSets *ToolSets `json:"toolSets,omitempty"`
	// Top level modes to run GleanChat in.
	Mode *Mode `json:"mode,omitempty"`
	// Whether the agent should create an image.
	UseImageGeneration *bool `json:"useImageGeneration,omitempty"`
}

func (a *AgentConfig) GetAgent() *AgentEnum {
	if a == nil {
		return nil
	}
	return a.Agent
}

func (a *AgentConfig) GetToolSets() *ToolSets {
	if a == nil {
		return nil
	}
	return a.ToolSets
}

func (a *AgentConfig) GetMode() *Mode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AgentConfig) GetUseImageGeneration() *bool {
	if a == nil {
		return nil
	}
	return a.UseImageGeneration
}
