// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// AnonymousEventEventType - The nature of the event, for example "out of office".
type AnonymousEventEventType string

const (
	AnonymousEventEventTypeDefault     AnonymousEventEventType = "DEFAULT"
	AnonymousEventEventTypeOutOfOffice AnonymousEventEventType = "OUT_OF_OFFICE"
)

func (e AnonymousEventEventType) ToPointer() *AnonymousEventEventType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AnonymousEventEventType) IsExact() bool {
	if e != nil {
		switch *e {
		case "DEFAULT", "OUT_OF_OFFICE":
			return true
		}
	}
	return false
}

// AnonymousEvent - A generic, light-weight calendar event.
type AnonymousEvent struct {
	Time *TimeInterval `json:"time,omitempty"`
	// The nature of the event, for example "out of office".
	EventType *AnonymousEventEventType `json:"eventType,omitempty"`
}

func (a AnonymousEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnonymousEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnonymousEvent) GetTime() *TimeInterval {
	if a == nil {
		return nil
	}
	return a.Time
}

func (a *AnonymousEvent) GetEventType() *AnonymousEventEventType {
	if a == nil {
		return nil
	}
	return a.EventType
}
