// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnswerResult struct {
	Answer Answer `json:"answer"`
	// An opaque token that represents this particular Answer. To be used for `/feedback` reporting.
	TrackingToken *string `json:"trackingToken,omitempty"`
}

func (a *AnswerResult) GetAnswer() Answer {
	if a == nil {
		return Answer{}
	}
	return a.Answer
}

func (a *AnswerResult) GetTrackingToken() *string {
	if a == nil {
		return nil
	}
	return a.TrackingToken
}
