// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

type AnswerSourceType string

const (
	AnswerSourceTypeDocument  AnswerSourceType = "DOCUMENT"
	AnswerSourceTypeAssistant AnswerSourceType = "ASSISTANT"
)

func (e AnswerSourceType) ToPointer() *AnswerSourceType {
	return &e
}
func (e *AnswerSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCUMENT":
		fallthrough
	case "ASSISTANT":
		*e = AnswerSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnswerSourceType: %v", v)
	}
}

type Answer struct {
	// The opaque ID of the Answer.
	ID int64 `json:"id"`
	// Glean Document ID of the Answer. The Glean Document ID is supported for cases where the Answer ID isn't available. If both are available, using the Answer ID is preferred.
	DocID    *string `json:"docId,omitempty"`
	Question *string `json:"question,omitempty"`
	// Additional ways of phrasing this question.
	QuestionVariations []string `json:"questionVariations,omitempty"`
	// The plain text answer to the question.
	BodyText *string `json:"bodyText,omitempty"`
	// The parent board ID of this Answer, or 0 if it's a floating Answer. Adding Answers to Answer Boards is no longer permitted.
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Answer Boards no longer supported.
	BoardID *int64 `json:"boardId,omitempty"`
	// Filters which restrict who should see the answer. Values are taken from the corresponding filters in people search.
	AudienceFilters []FacetFilter `json:"audienceFilters,omitempty"`
	// A list of user roles for the answer added by the owner.
	AddedRoles []UserRoleSpecification `json:"addedRoles,omitempty"`
	// A list of user roles for the answer removed by the owner.
	RemovedRoles []UserRoleSpecification `json:"removedRoles,omitempty"`
	// A list of roles for this answer explicitly granted by an owner, editor, or admin.
	Roles              []UserRoleSpecification `json:"roles,omitempty"`
	SourceDocumentSpec *DocumentSpecUnion      `json:"sourceDocumentSpec,omitempty"`
	SourceType         *AnswerSourceType       `json:"sourceType,omitempty"`
	Permissions        *ObjectPermissions      `json:"permissions,omitempty"`
	CombinedAnswerText *StructuredText         `json:"combinedAnswerText,omitempty"`
	Likes              *AnswerLikes            `json:"likes,omitempty"`
	Author             *Person                 `json:"author,omitempty"`
	// The time the answer was created in ISO format (ISO 8601).
	CreateTime *time.Time `json:"createTime,omitempty"`
	// The time the answer was last updated in ISO format (ISO 8601).
	UpdateTime   *time.Time    `json:"updateTime,omitempty"`
	UpdatedBy    *Person       `json:"updatedBy,omitempty"`
	Verification *Verification `json:"verification,omitempty"`
	// The collections to which the answer belongs.
	Collections []Collection `json:"collections,omitempty"`
	// The document's document_category(.proto).
	DocumentCategory *string   `json:"documentCategory,omitempty"`
	SourceDocument   *Document `json:"sourceDocument,omitempty"`
}

func (a Answer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Answer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (a *Answer) GetID() int64 {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *Answer) GetDocID() *string {
	if a == nil {
		return nil
	}
	return a.DocID
}

func (a *Answer) GetQuestion() *string {
	if a == nil {
		return nil
	}
	return a.Question
}

func (a *Answer) GetQuestionVariations() []string {
	if a == nil {
		return nil
	}
	return a.QuestionVariations
}

func (a *Answer) GetBodyText() *string {
	if a == nil {
		return nil
	}
	return a.BodyText
}

func (a *Answer) GetBoardID() *int64 {
	if a == nil {
		return nil
	}
	return a.BoardID
}

func (a *Answer) GetAudienceFilters() []FacetFilter {
	if a == nil {
		return nil
	}
	return a.AudienceFilters
}

func (a *Answer) GetAddedRoles() []UserRoleSpecification {
	if a == nil {
		return nil
	}
	return a.AddedRoles
}

func (a *Answer) GetRemovedRoles() []UserRoleSpecification {
	if a == nil {
		return nil
	}
	return a.RemovedRoles
}

func (a *Answer) GetRoles() []UserRoleSpecification {
	if a == nil {
		return nil
	}
	return a.Roles
}

func (a *Answer) GetSourceDocumentSpec() *DocumentSpecUnion {
	if a == nil {
		return nil
	}
	return a.SourceDocumentSpec
}

func (a *Answer) GetSourceType() *AnswerSourceType {
	if a == nil {
		return nil
	}
	return a.SourceType
}

func (a *Answer) GetPermissions() *ObjectPermissions {
	if a == nil {
		return nil
	}
	return a.Permissions
}

func (a *Answer) GetCombinedAnswerText() *StructuredText {
	if a == nil {
		return nil
	}
	return a.CombinedAnswerText
}

func (a *Answer) GetLikes() *AnswerLikes {
	if a == nil {
		return nil
	}
	return a.Likes
}

func (a *Answer) GetAuthor() *Person {
	if a == nil {
		return nil
	}
	return a.Author
}

func (a *Answer) GetCreateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreateTime
}

func (a *Answer) GetUpdateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdateTime
}

func (a *Answer) GetUpdatedBy() *Person {
	if a == nil {
		return nil
	}
	return a.UpdatedBy
}

func (a *Answer) GetVerification() *Verification {
	if a == nil {
		return nil
	}
	return a.Verification
}

func (a *Answer) GetCollections() []Collection {
	if a == nil {
		return nil
	}
	return a.Collections
}

func (a *Answer) GetDocumentCategory() *string {
	if a == nil {
		return nil
	}
	return a.DocumentCategory
}

func (a *Answer) GetSourceDocument() *Document {
	if a == nil {
		return nil
	}
	return a.SourceDocument
}
