// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type AppResult struct {
	// The app or other repository type this represents
	Datasource string `json:"datasource"`
	// The datasource-specific type of the document (e.g. for Jira issues, this is the issue type such as Bug or Feature Request).
	DocType *string `json:"docType,omitempty"`
	// Mimetype is used to differentiate between sub applications from a datasource (e.g. Sheets, Docs from Gdrive)
	MimeType *string `json:"mimeType,omitempty"`
	// If there is available icon URL.
	IconURL *string `json:"iconUrl,omitempty"`
}

func (a AppResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"datasource"}); err != nil {
		return err
	}
	return nil
}

func (a *AppResult) GetDatasource() string {
	if a == nil {
		return ""
	}
	return a.Datasource
}

func (a *AppResult) GetDocType() *string {
	if a == nil {
		return nil
	}
	return a.DocType
}

func (a *AppResult) GetMimeType() *string {
	if a == nil {
		return nil
	}
	return a.MimeType
}

func (a *AppResult) GetIconURL() *string {
	if a == nil {
		return nil
	}
	return a.IconURL
}
