// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthStatus - The per-user authorization status for a datasource.
type AuthStatus string

const (
	AuthStatusDisabled     AuthStatus = "DISABLED"
	AuthStatusAwaitingAuth AuthStatus = "AWAITING_AUTH"
	AuthStatusAuthorized   AuthStatus = "AUTHORIZED"
	AuthStatusStaleOauth   AuthStatus = "STALE_OAUTH"
	AuthStatusSegMigration AuthStatus = "SEG_MIGRATION"
)

func (e AuthStatus) ToPointer() *AuthStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "DISABLED", "AWAITING_AUTH", "AUTHORIZED", "STALE_OAUTH", "SEG_MIGRATION":
			return true
		}
	}
	return false
}
