// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BulkIndexEmployeesRequest - Describes the request body of the /bulkindexemployees API call
type BulkIndexEmployeesRequest struct {
	// Unique id that must be used for this bulk upload instance
	UploadID string `json:"uploadId"`
	// true if this is the first page of the upload. Defaults to false
	IsFirstPage *bool `json:"isFirstPage,omitempty"`
	// true if this is the last page of the upload. Defaults to false
	IsLastPage *bool `json:"isLastPage,omitempty"`
	// Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
	ForceRestartUpload *bool `json:"forceRestartUpload,omitempty"`
	// Batch of employee information
	Employees []EmployeeInfoDefinition `json:"employees"`
	// True if older employee data needs to be force deleted after the upload completes. Defaults to older data being deleted only if the percentage of data being deleted is less than 20%. This must only be set when `isLastPage = true`
	DisableStaleDataDeletionCheck *bool `json:"disableStaleDataDeletionCheck,omitempty"`
}

func (b *BulkIndexEmployeesRequest) GetUploadID() string {
	if b == nil {
		return ""
	}
	return b.UploadID
}

func (b *BulkIndexEmployeesRequest) GetIsFirstPage() *bool {
	if b == nil {
		return nil
	}
	return b.IsFirstPage
}

func (b *BulkIndexEmployeesRequest) GetIsLastPage() *bool {
	if b == nil {
		return nil
	}
	return b.IsLastPage
}

func (b *BulkIndexEmployeesRequest) GetForceRestartUpload() *bool {
	if b == nil {
		return nil
	}
	return b.ForceRestartUpload
}

func (b *BulkIndexEmployeesRequest) GetEmployees() []EmployeeInfoDefinition {
	if b == nil {
		return []EmployeeInfoDefinition{}
	}
	return b.Employees
}

func (b *BulkIndexEmployeesRequest) GetDisableStaleDataDeletionCheck() *bool {
	if b == nil {
		return nil
	}
	return b.DisableStaleDataDeletionCheck
}
