// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type ResponseStatus string

const (
	ResponseStatusAccepted   ResponseStatus = "ACCEPTED"
	ResponseStatusDeclined   ResponseStatus = "DECLINED"
	ResponseStatusNoResponse ResponseStatus = "NO_RESPONSE"
	ResponseStatusTentative  ResponseStatus = "TENTATIVE"
)

func (e ResponseStatus) ToPointer() *ResponseStatus {
	return &e
}
func (e *ResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCEPTED":
		fallthrough
	case "DECLINED":
		fallthrough
	case "NO_RESPONSE":
		fallthrough
	case "TENTATIVE":
		*e = ResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseStatus: %v", v)
	}
}

type CalendarAttendee struct {
	// Whether or not this attendee is an organizer.
	IsOrganizer *bool `json:"isOrganizer,omitempty"`
	// Whether or not this attendee is in a group. Needed temporarily at least to support both flat attendees and tree for compatibility.
	IsInGroup *bool  `json:"isInGroup,omitempty"`
	Person    Person `json:"person"`
	// If this attendee is a group, represents the list of individual attendees in the group.
	GroupAttendees []CalendarAttendee `json:"groupAttendees,omitempty"`
	ResponseStatus *ResponseStatus    `json:"responseStatus,omitempty"`
}

func (c CalendarAttendee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CalendarAttendee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"person"}); err != nil {
		return err
	}
	return nil
}

func (c *CalendarAttendee) GetIsOrganizer() *bool {
	if c == nil {
		return nil
	}
	return c.IsOrganizer
}

func (c *CalendarAttendee) GetIsInGroup() *bool {
	if c == nil {
		return nil
	}
	return c.IsInGroup
}

func (c *CalendarAttendee) GetPerson() Person {
	if c == nil {
		return Person{}
	}
	return c.Person
}

func (c *CalendarAttendee) GetGroupAttendees() []CalendarAttendee {
	if c == nil {
		return nil
	}
	return c.GroupAttendees
}

func (c *CalendarAttendee) GetResponseStatus() *ResponseStatus {
	if c == nil {
		return nil
	}
	return c.ResponseStatus
}
