// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatFileFailureReason - Reason for failed status.
type ChatFileFailureReason string

const (
	ChatFileFailureReasonParseFailed                ChatFileFailureReason = "PARSE_FAILED"
	ChatFileFailureReasonAvScanFailed               ChatFileFailureReason = "AV_SCAN_FAILED"
	ChatFileFailureReasonFileTooSmall               ChatFileFailureReason = "FILE_TOO_SMALL"
	ChatFileFailureReasonFileTooLarge               ChatFileFailureReason = "FILE_TOO_LARGE"
	ChatFileFailureReasonFileExtensionUnsupported   ChatFileFailureReason = "FILE_EXTENSION_UNSUPPORTED"
	ChatFileFailureReasonFileMetadataValidationFail ChatFileFailureReason = "FILE_METADATA_VALIDATION_FAIL"
	ChatFileFailureReasonFileProcessingTimedOut     ChatFileFailureReason = "FILE_PROCESSING_TIMED_OUT"
	ChatFileFailureReasonOauthNeeded                ChatFileFailureReason = "OAUTH_NEEDED"
	ChatFileFailureReasonURLFetchFailed             ChatFileFailureReason = "URL_FETCH_FAILED"
	ChatFileFailureReasonEmptyContent               ChatFileFailureReason = "EMPTY_CONTENT"
	ChatFileFailureReasonAuthRequired               ChatFileFailureReason = "AUTH_REQUIRED"
)

func (e ChatFileFailureReason) ToPointer() *ChatFileFailureReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ChatFileFailureReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "PARSE_FAILED", "AV_SCAN_FAILED", "FILE_TOO_SMALL", "FILE_TOO_LARGE", "FILE_EXTENSION_UNSUPPORTED", "FILE_METADATA_VALIDATION_FAIL", "FILE_PROCESSING_TIMED_OUT", "OAUTH_NEEDED", "URL_FETCH_FAILED", "EMPTY_CONTENT", "AUTH_REQUIRED":
			return true
		}
	}
	return false
}
