// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// ChatMetadata - Metadata of a Chat a user had with Glean Assistant. This contains no actual conversational content.
type ChatMetadata struct {
	// The opaque id of the Chat.
	ID *string `json:"id,omitempty"`
	// Server Unix timestamp of the creation time (in seconds since epoch UTC).
	CreateTime *int64  `json:"createTime,omitempty"`
	CreatedBy  *Person `json:"createdBy,omitempty"`
	// Server Unix timestamp of the update time (in seconds since epoch UTC).
	UpdateTime *int64 `json:"updateTime,omitempty"`
	// The name of the Chat.
	Name *string `json:"name,omitempty"`
	// The ID of the AI App that this Chat is associated to.
	ApplicationID *string `json:"applicationId,omitempty"`
	// The display name of the AI App that this Chat is associated to.
	ApplicationName *string `json:"applicationName,omitempty"`
	// Defines how to render an icon
	Icon *IconConfig `json:"icon,omitempty"`
}

func (c ChatMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatMetadata) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChatMetadata) GetCreateTime() *int64 {
	if c == nil {
		return nil
	}
	return c.CreateTime
}

func (c *ChatMetadata) GetCreatedBy() *Person {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *ChatMetadata) GetUpdateTime() *int64 {
	if c == nil {
		return nil
	}
	return c.UpdateTime
}

func (c *ChatMetadata) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ChatMetadata) GetApplicationID() *string {
	if c == nil {
		return nil
	}
	return c.ApplicationID
}

func (c *ChatMetadata) GetApplicationName() *string {
	if c == nil {
		return nil
	}
	return c.ApplicationName
}

func (c *ChatMetadata) GetIcon() *IconConfig {
	if c == nil {
		return nil
	}
	return c.Icon
}
