// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type Code struct {
	RepoName *string    `json:"repoName,omitempty"`
	FileName *string    `json:"fileName,omitempty"`
	FileURL  *string    `json:"fileUrl,omitempty"`
	Lines    []CodeLine `json:"lines,omitempty"`
	// Last file match for a repo
	IsLastMatch *bool `json:"isLastMatch,omitempty"`
}

func (c Code) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Code) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Code) GetRepoName() *string {
	if c == nil {
		return nil
	}
	return c.RepoName
}

func (c *Code) GetFileName() *string {
	if c == nil {
		return nil
	}
	return c.FileName
}

func (c *Code) GetFileURL() *string {
	if c == nil {
		return nil
	}
	return c.FileURL
}

func (c *Code) GetLines() []CodeLine {
	if c == nil {
		return nil
	}
	return c.Lines
}

func (c *Code) GetIsLastMatch() *bool {
	if c == nil {
		return nil
	}
	return c.IsLastMatch
}
