// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

type CollectionItemItemType string

const (
	CollectionItemItemTypeDocument   CollectionItemItemType = "DOCUMENT"
	CollectionItemItemTypeText       CollectionItemItemType = "TEXT"
	CollectionItemItemTypeURL        CollectionItemItemType = "URL"
	CollectionItemItemTypeCollection CollectionItemItemType = "COLLECTION"
)

func (e CollectionItemItemType) ToPointer() *CollectionItemItemType {
	return &e
}
func (e *CollectionItemItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCUMENT":
		fallthrough
	case "TEXT":
		fallthrough
	case "URL":
		fallthrough
	case "COLLECTION":
		*e = CollectionItemItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CollectionItemItemType: %v", v)
	}
}

type CollectionItem struct {
	// The optional name of the Collection item.
	Name *string `json:"name,omitempty"`
	// A helpful description of why this CollectionItem is in the Collection that it's in.
	Description *string `json:"description,omitempty"`
	// The emoji icon for this CollectionItem. Only used for Text type items.
	Icon *string `json:"icon,omitempty"`
	// The Collection ID of the Collection that this CollectionItem belongs in.
	CollectionID int64 `json:"collectionId"`
	// If this CollectionItem is indexed, the Glean Document ID of that document.
	DocumentID *string `json:"documentId,omitempty"`
	// The URL of this CollectionItem.
	URL *string `json:"url,omitempty"`
	// Unique identifier for the item within the Collection it belongs to.
	ItemID    *string `json:"itemId,omitempty"`
	CreatedBy *Person `json:"createdBy,omitempty"`
	// Unix timestamp for when the item was first added (in seconds since epoch UTC).
	CreatedAt  *time.Time             `json:"createdAt,omitempty"`
	Document   *Document              `json:"document,omitempty"`
	Shortcut   *Shortcut              `json:"shortcut,omitempty"`
	Collection *Collection            `json:"collection,omitempty"`
	ItemType   CollectionItemItemType `json:"itemType"`
}

func (c CollectionItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectionItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"collectionId", "itemType"}); err != nil {
		return err
	}
	return nil
}

func (c *CollectionItem) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CollectionItem) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CollectionItem) GetIcon() *string {
	if c == nil {
		return nil
	}
	return c.Icon
}

func (c *CollectionItem) GetCollectionID() int64 {
	if c == nil {
		return 0
	}
	return c.CollectionID
}

func (c *CollectionItem) GetDocumentID() *string {
	if c == nil {
		return nil
	}
	return c.DocumentID
}

func (c *CollectionItem) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}

func (c *CollectionItem) GetItemID() *string {
	if c == nil {
		return nil
	}
	return c.ItemID
}

func (c *CollectionItem) GetCreatedBy() *Person {
	if c == nil {
		return nil
	}
	return c.CreatedBy
}

func (c *CollectionItem) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *CollectionItem) GetDocument() *Document {
	if c == nil {
		return nil
	}
	return c.Document
}

func (c *CollectionItem) GetShortcut() *Shortcut {
	if c == nil {
		return nil
	}
	return c.Shortcut
}

func (c *CollectionItem) GetCollection() *Collection {
	if c == nil {
		return nil
	}
	return c.Collection
}

func (c *CollectionItem) GetItemType() CollectionItemItemType {
	if c == nil {
		return CollectionItemItemType("")
	}
	return c.ItemType
}
