// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type CountInfo struct {
	// The counter value
	Count  int64   `json:"count"`
	Period *Period `json:"period,omitempty"`
	// The unit of organization over which we did the count aggregation, e.g. org (department) or company
	Org *string `json:"org,omitempty"`
}

func (c CountInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CountInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"count"}); err != nil {
		return err
	}
	return nil
}

func (c *CountInfo) GetCount() int64 {
	if c == nil {
		return 0
	}
	return c.Count
}

func (c *CountInfo) GetPeriod() *Period {
	if c == nil {
		return nil
	}
	return c.Period
}

func (c *CountInfo) GetOrg() *string {
	if c == nil {
		return nil
	}
	return c.Org
}
