// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateAuthTokenResponse struct {
	// An authentication token that can be passed to any endpoint via Bearer Authentication
	Token string `json:"token"`
	// Unix timestamp for when this token expires (in seconds since epoch UTC).
	ExpirationTime int64 `json:"expirationTime"`
}

func (c *CreateAuthTokenResponse) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CreateAuthTokenResponse) GetExpirationTime() int64 {
	if c == nil {
		return 0
	}
	return c.ExpirationTime
}
