// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateShortcutRequest struct {
	Data ShortcutMutableProperties `json:"data"`
}

func (c *CreateShortcutRequest) GetData() ShortcutMutableProperties {
	if c == nil {
		return ShortcutMutableProperties{}
	}
	return c.Data
}
