// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDlpReportRequest struct {
	// Name of the policy being created.
	Name *string `json:"name,omitempty"`
	// Detailed configuration of what documents and sensitive content will be scanned.
	Config *DlpConfig `json:"config,omitempty"`
	// Interval between scans. DAILY is deprecated.
	Frequency *DlpFrequency `json:"frequency,omitempty"`
	// Controls whether the policy should hide documents with violations.
	AutoHideDocs *bool `json:"autoHideDocs,omitempty"`
}

func (c *CreateDlpReportRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateDlpReportRequest) GetConfig() *DlpConfig {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *CreateDlpReportRequest) GetFrequency() *DlpFrequency {
	if c == nil {
		return nil
	}
	return c.Frequency
}

func (c *CreateDlpReportRequest) GetAutoHideDocs() *bool {
	if c == nil {
		return nil
	}
	return c.AutoHideDocs
}
