// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateShortcutResponse struct {
	Shortcut *Shortcut      `json:"shortcut,omitempty"`
	Error    *ShortcutError `json:"error,omitempty"`
}

func (c *CreateShortcutResponse) GetShortcut() *Shortcut {
	if c == nil {
		return nil
	}
	return c.Shortcut
}

func (c *CreateShortcutResponse) GetError() *ShortcutError {
	if c == nil {
		return nil
	}
	return c.Error
}
