// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type CustomFieldValuePerson struct {
	Person *Person `json:"person,omitempty"`
}

func (c CustomFieldValuePerson) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomFieldValuePerson) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomFieldValuePerson) GetPerson() *Person {
	if c == nil {
		return nil
	}
	return c.Person
}
