// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DatasourceConfigurationResponse - The greenlisted configuration values for a datasource instance. Only keys that are exposed via the public API greenlist are included.
type DatasourceConfigurationResponse struct {
	// Configuration for a datasource instance
	Configuration DatasourceInstanceConfiguration `json:"configuration"`
}

func (d *DatasourceConfigurationResponse) GetConfiguration() DatasourceInstanceConfiguration {
	if d == nil {
		return DatasourceInstanceConfiguration{}
	}
	return d.Configuration
}
