// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DatasourceInstanceConfiguration - Configuration for a datasource instance
type DatasourceInstanceConfiguration struct {
	// A map from configuration key names to their values
	Values map[string]ConfigurationValue `json:"values"`
}

func (d *DatasourceInstanceConfiguration) GetValues() map[string]ConfigurationValue {
	if d == nil {
		return map[string]ConfigurationValue{}
	}
	return d.Values
}
