// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type DatasourceProfile struct {
	// The datasource the profile is of.
	Datasource string `json:"datasource"`
	// The display name of the entity in the given datasource.
	Handle string `json:"handle"`
	// URL to view the entity's profile.
	URL *string `json:"url,omitempty"`
	// A deep link, if available, into the datasource's native application for the entity's platform (i.e. slack://...).
	NativeAppURL *string `json:"nativeAppUrl,omitempty"`
	// For internal use only. True iff the data source profile was manually added by a user from within Glean (aka not from the original data source)
	IsUserGenerated *bool `json:"isUserGenerated,omitempty"`
}

func (d DatasourceProfile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasourceProfile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"datasource", "handle"}); err != nil {
		return err
	}
	return nil
}

func (d *DatasourceProfile) GetDatasource() string {
	if d == nil {
		return ""
	}
	return d.Datasource
}

func (d *DatasourceProfile) GetHandle() string {
	if d == nil {
		return ""
	}
	return d.Handle
}

func (d *DatasourceProfile) GetURL() *string {
	if d == nil {
		return nil
	}
	return d.URL
}

func (d *DatasourceProfile) GetNativeAppURL() *string {
	if d == nil {
		return nil
	}
	return d.NativeAppURL
}

func (d *DatasourceProfile) GetIsUserGenerated() *bool {
	if d == nil {
		return nil
	}
	return d.IsUserGenerated
}
