// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DatasourceMembershipDefinition - describes the membership row of a group. Only one of memberUserId and memberGroupName can be specified.
type DatasourceMembershipDefinition struct {
	// The group for which the membership is specified
	GroupName string `json:"groupName"`
	// If the member is a user, then the email or datasource id for the user
	MemberUserID *string `json:"memberUserId,omitempty"`
	// If the member is a group, then the name of the member group
	MemberGroupName *string `json:"memberGroupName,omitempty"`
}

func (d *DatasourceMembershipDefinition) GetGroupName() string {
	if d == nil {
		return ""
	}
	return d.GroupName
}

func (d *DatasourceMembershipDefinition) GetMemberUserID() *string {
	if d == nil {
		return nil
	}
	return d.MemberUserID
}

func (d *DatasourceMembershipDefinition) GetMemberGroupName() *string {
	if d == nil {
		return nil
	}
	return d.MemberGroupName
}
