// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DebugDatasourceStatusResponseCounts struct {
	// A list of object types and corresponding upload counts. Note: This data may be cached and could be up to 3 hours stale.
	//
	Uploaded []DatasourceObjectTypeDocumentCountEntry `json:"uploaded,omitempty"`
	// The number of documents indexed, grouped by objectType
	Indexed []DatasourceObjectTypeDocumentCountEntry `json:"indexed,omitempty"`
}

func (d *DebugDatasourceStatusResponseCounts) GetUploaded() []DatasourceObjectTypeDocumentCountEntry {
	if d == nil {
		return nil
	}
	return d.Uploaded
}

func (d *DebugDatasourceStatusResponseCounts) GetIndexed() []DatasourceObjectTypeDocumentCountEntry {
	if d == nil {
		return nil
	}
	return d.Indexed
}

type Documents struct {
	// Information about active and recent successful uploads for the datasource
	BulkUploadHistory []BulkUploadHistoryEvent             `json:"bulkUploadHistory,omitempty"`
	Counts            *DebugDatasourceStatusResponseCounts `json:"counts,omitempty"`
	// Information about processing history for the datasource
	ProcessingHistory []ProcessingHistoryEvent `json:"processingHistory,omitempty"`
}

func (d *Documents) GetBulkUploadHistory() []BulkUploadHistoryEvent {
	if d == nil {
		return nil
	}
	return d.BulkUploadHistory
}

func (d *Documents) GetCounts() *DebugDatasourceStatusResponseCounts {
	if d == nil {
		return nil
	}
	return d.Counts
}

func (d *Documents) GetProcessingHistory() []ProcessingHistoryEvent {
	if d == nil {
		return nil
	}
	return d.ProcessingHistory
}

type Identity struct {
	// Information about processing history for the datasource
	ProcessingHistory []ProcessingHistoryEvent                        `json:"processingHistory,omitempty"`
	Users             *DebugDatasourceStatusIdentityResponseComponent `json:"users,omitempty"`
	Groups            *DebugDatasourceStatusIdentityResponseComponent `json:"groups,omitempty"`
	Memberships       *DebugDatasourceStatusIdentityResponseComponent `json:"memberships,omitempty"`
}

func (i *Identity) GetProcessingHistory() []ProcessingHistoryEvent {
	if i == nil {
		return nil
	}
	return i.ProcessingHistory
}

func (i *Identity) GetUsers() *DebugDatasourceStatusIdentityResponseComponent {
	if i == nil {
		return nil
	}
	return i.Users
}

func (i *Identity) GetGroups() *DebugDatasourceStatusIdentityResponseComponent {
	if i == nil {
		return nil
	}
	return i.Groups
}

func (i *Identity) GetMemberships() *DebugDatasourceStatusIdentityResponseComponent {
	if i == nil {
		return nil
	}
	return i.Memberships
}

// DatasourceVisibility - The visibility of the datasource, an enum of VISIBLE_TO_ALL, VISIBLE_TO_TEST_GROUP, NOT_VISIBLE
type DatasourceVisibility string

const (
	DatasourceVisibilityEnabledForAll       DatasourceVisibility = "ENABLED_FOR_ALL"
	DatasourceVisibilityEnabledForTestGroup DatasourceVisibility = "ENABLED_FOR_TEST_GROUP"
	DatasourceVisibilityNotEnabled          DatasourceVisibility = "NOT_ENABLED"
)

func (e DatasourceVisibility) ToPointer() *DatasourceVisibility {
	return &e
}
func (e *DatasourceVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ENABLED_FOR_ALL":
		fallthrough
	case "ENABLED_FOR_TEST_GROUP":
		fallthrough
	case "NOT_ENABLED":
		*e = DatasourceVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DatasourceVisibility: %v", v)
	}
}

// DebugDatasourceStatusResponse - Describes the response body of the /debug/{datasource}/status API call
type DebugDatasourceStatusResponse struct {
	Documents *Documents `json:"documents,omitempty"`
	Identity  *Identity  `json:"identity,omitempty"`
	// The visibility of the datasource, an enum of VISIBLE_TO_ALL, VISIBLE_TO_TEST_GROUP, NOT_VISIBLE
	DatasourceVisibility *DatasourceVisibility `json:"datasourceVisibility,omitempty"`
}

func (d *DebugDatasourceStatusResponse) GetDocuments() *Documents {
	if d == nil {
		return nil
	}
	return d.Documents
}

func (d *DebugDatasourceStatusResponse) GetIdentity() *Identity {
	if d == nil {
		return nil
	}
	return d.Identity
}

func (d *DebugDatasourceStatusResponse) GetDatasourceVisibility() *DatasourceVisibility {
	if d == nil {
		return nil
	}
	return d.DatasourceVisibility
}
