// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DebugDocumentResponse - Describes the response body of the /debug/{datasource}/document API call
type DebugDocumentResponse struct {
	// Describes the document status response body
	Status *DocumentStatusResponse `json:"status,omitempty"`
	// describes the access control details of the document
	UploadedPermissions *DocumentPermissionsDefinition `json:"uploadedPermissions,omitempty"`
}

func (d *DebugDocumentResponse) GetStatus() *DocumentStatusResponse {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DebugDocumentResponse) GetUploadedPermissions() *DocumentPermissionsDefinition {
	if d == nil {
		return nil
	}
	return d.UploadedPermissions
}
