// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteCollectionItemResponse struct {
	Collection *Collection `json:"collection,omitempty"`
}

func (d *DeleteCollectionItemResponse) GetCollection() *Collection {
	if d == nil {
		return nil
	}
	return d.Collection
}
