// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeleteTeamRequest - Describes the request body of the /deleteteam API call
type DeleteTeamRequest struct {
	// The deleted team's id
	ID string `json:"id"`
}

func (d *DeleteTeamRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
