// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeleteGroupRequest - Describes the request body of the /deletegroup API call
type DeleteGroupRequest struct {
	// Version number for document for optimistic concurrency control. If absent or 0 then no version checks are done.
	Version *int64 `json:"version,omitempty"`
	// The datasource for which the group is removed
	Datasource string `json:"datasource"`
	// the name of the group to be deleted
	GroupName string `json:"groupName"`
}

func (d *DeleteGroupRequest) GetVersion() *int64 {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DeleteGroupRequest) GetDatasource() string {
	if d == nil {
		return ""
	}
	return d.Datasource
}

func (d *DeleteGroupRequest) GetGroupName() string {
	if d == nil {
		return ""
	}
	return d.GroupName
}
