// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DlpFrequency - Interval between scans. DAILY is deprecated.
type DlpFrequency string

const (
	DlpFrequencyOnce       DlpFrequency = "ONCE"
	DlpFrequencyDaily      DlpFrequency = "DAILY"
	DlpFrequencyWeekly     DlpFrequency = "WEEKLY"
	DlpFrequencyContinuous DlpFrequency = "CONTINUOUS"
	DlpFrequencyNone       DlpFrequency = "NONE"
)

func (e DlpFrequency) ToPointer() *DlpFrequency {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DlpFrequency) IsExact() bool {
	if e != nil {
		switch *e {
		case "ONCE", "DAILY", "WEEKLY", "CONTINUOUS", "NONE":
			return true
		}
	}
	return false
}
