// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DlpReportStatus - The status of the policy/report. Only ACTIVE status will be picked for scans.
type DlpReportStatus string

const (
	DlpReportStatusActive    DlpReportStatus = "ACTIVE"
	DlpReportStatusInactive  DlpReportStatus = "INACTIVE"
	DlpReportStatusCancelled DlpReportStatus = "CANCELLED"
	DlpReportStatusNone      DlpReportStatus = "NONE"
)

func (e DlpReportStatus) ToPointer() *DlpReportStatus {
	return &e
}
func (e *DlpReportStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTIVE":
		fallthrough
	case "INACTIVE":
		fallthrough
	case "CANCELLED":
		fallthrough
	case "NONE":
		*e = DlpReportStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DlpReportStatus: %v", v)
	}
}
