// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DocumentVisibility - The level of visibility of the document as understood by our system.
type DocumentVisibility string

const (
	// DocumentVisibilityPrivate Only one person is able to see the document.
	DocumentVisibilityPrivate DocumentVisibility = "PRIVATE"
	// DocumentVisibilitySpecificPeopleAndGroups Only specific people and/or groups can see the document.
	DocumentVisibilitySpecificPeopleAndGroups DocumentVisibility = "SPECIFIC_PEOPLE_AND_GROUPS"
	// DocumentVisibilityDomainLink Anyone in the domain with the link can see the document.
	DocumentVisibilityDomainLink DocumentVisibility = "DOMAIN_LINK"
	// DocumentVisibilityDomainVisible Anyone in the domain can search for the document.
	DocumentVisibilityDomainVisible DocumentVisibility = "DOMAIN_VISIBLE"
	// DocumentVisibilityPublicLink Anyone with the link can see the document.
	DocumentVisibilityPublicLink DocumentVisibility = "PUBLIC_LINK"
	// DocumentVisibilityPublicVisible Anyone on the internet can search for the document.
	DocumentVisibilityPublicVisible DocumentVisibility = "PUBLIC_VISIBLE"
)

func (e DocumentVisibility) ToPointer() *DocumentVisibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DocumentVisibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "PRIVATE", "SPECIFIC_PEOPLE_AND_GROUPS", "DOMAIN_LINK", "DOMAIN_VISIBLE", "PUBLIC_LINK", "PUBLIC_VISIBLE":
			return true
		}
	}
	return false
}
