// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DocumentVisibility - The level of visibility of the document as understood by our system.
type DocumentVisibility string

const (
	// DocumentVisibilityPrivate Only one person is able to see the document.
	DocumentVisibilityPrivate DocumentVisibility = "PRIVATE"
	// DocumentVisibilitySpecificPeopleAndGroups Only specific people and/or groups can see the document.
	DocumentVisibilitySpecificPeopleAndGroups DocumentVisibility = "SPECIFIC_PEOPLE_AND_GROUPS"
	// DocumentVisibilityDomainLink Anyone in the domain with the link can see the document.
	DocumentVisibilityDomainLink DocumentVisibility = "DOMAIN_LINK"
	// DocumentVisibilityDomainVisible Anyone in the domain can search for the document.
	DocumentVisibilityDomainVisible DocumentVisibility = "DOMAIN_VISIBLE"
	// DocumentVisibilityPublicLink Anyone with the link can see the document.
	DocumentVisibilityPublicLink DocumentVisibility = "PUBLIC_LINK"
	// DocumentVisibilityPublicVisible Anyone on the internet can search for the document.
	DocumentVisibilityPublicVisible DocumentVisibility = "PUBLIC_VISIBLE"
)

func (e DocumentVisibility) ToPointer() *DocumentVisibility {
	return &e
}
func (e *DocumentVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PRIVATE":
		fallthrough
	case "SPECIFIC_PEOPLE_AND_GROUPS":
		fallthrough
	case "DOMAIN_LINK":
		fallthrough
	case "DOMAIN_VISIBLE":
		fallthrough
	case "PUBLIC_LINK":
		fallthrough
	case "PUBLIC_VISIBLE":
		*e = DocumentVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentVisibility: %v", v)
	}
}
