// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type DocumentOrError struct {
	// The text for error, reason.
	Error string `json:"error"`
}

func (d DocumentOrError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentOrError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DocumentOrError) GetError() string {
	if d == nil {
		return ""
	}
	return d.Error
}

type DocumentOrErrorUnionType string

const (
	DocumentOrErrorUnionTypeDocument        DocumentOrErrorUnionType = "Document"
	DocumentOrErrorUnionTypeDocumentOrError DocumentOrErrorUnionType = "DocumentOrError"
)

type DocumentOrErrorUnion struct {
	Document        *Document        `queryParam:"inline" union:"member"`
	DocumentOrError *DocumentOrError `queryParam:"inline" union:"member"`

	Type DocumentOrErrorUnionType
}

func CreateDocumentOrErrorUnionDocument(document Document) DocumentOrErrorUnion {
	typ := DocumentOrErrorUnionTypeDocument

	return DocumentOrErrorUnion{
		Document: &document,
		Type:     typ,
	}
}

func CreateDocumentOrErrorUnionDocumentOrError(documentOrError DocumentOrError) DocumentOrErrorUnion {
	typ := DocumentOrErrorUnionTypeDocumentOrError

	return DocumentOrErrorUnion{
		DocumentOrError: &documentOrError,
		Type:            typ,
	}
}

func (u *DocumentOrErrorUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var document Document = Document{}
	if err := utils.UnmarshalJSON(data, &document, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  DocumentOrErrorUnionTypeDocument,
			Value: &document,
		})
	}

	var documentOrError DocumentOrError = DocumentOrError{}
	if err := utils.UnmarshalJSON(data, &documentOrError, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  DocumentOrErrorUnionTypeDocumentOrError,
			Value: &documentOrError,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentOrErrorUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentOrErrorUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(DocumentOrErrorUnionType)
	switch best.Type {
	case DocumentOrErrorUnionTypeDocument:
		u.Document = best.Value.(*Document)
		return nil
	case DocumentOrErrorUnionTypeDocumentOrError:
		u.DocumentOrError = best.Value.(*DocumentOrError)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentOrErrorUnion", string(data))
}

func (u DocumentOrErrorUnion) MarshalJSON() ([]byte, error) {
	if u.Document != nil {
		return utils.MarshalJSON(u.Document, "", true)
	}

	if u.DocumentOrError != nil {
		return utils.MarshalJSON(u.DocumentOrError, "", true)
	}

	return nil, errors.New("could not marshal union type DocumentOrErrorUnion: all fields are null")
}
