// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EditCollectionItemResponse struct {
	Collection *Collection `json:"collection,omitempty"`
}

func (e *EditCollectionItemResponse) GetCollection() *Collection {
	if e == nil {
		return nil
	}
	return e.Collection
}
