// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"github.com/gleanwork/api-client-go/types"
)

// EmployeeInfoDefinition - Describes employee info
type EmployeeInfoDefinition struct {
	// The employee's email
	Email string `json:"email"`
	// The first name of the employee. **Note**: The value cannot be empty
	//
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the employee. **Note**: The value cannot be empty
	//
	LastName *string `json:"lastName,omitempty"`
	// The preferred name or nickname of the employee
	PreferredName *string `json:"preferredName,omitempty"`
	// **[Advanced]** A unique universal internal identifier for the employee. This is solely used for understanding manager relationships along with `managerId`.
	//
	ID *string `json:"id,omitempty"`
	// The employee's phone number.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// The employee's location (city/office name etc).
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Field is deprecated.
	Location *string `json:"location,omitempty"`
	// Detailed location with information about country, state, city etc.
	StructuredLocation *StructuredLocation `json:"structuredLocation,omitempty"`
	// The employee's role title.
	Title *string `json:"title,omitempty"`
	// The employee's profile pic
	PhotoURL *string `json:"photoUrl,omitempty"`
	// Typically the highest level organizational unit; generally applies to bigger companies with multiple distinct businesses.
	BusinessUnit *string `json:"businessUnit,omitempty"`
	// An organizational unit where everyone has a similar task, e.g. `Engineering`.
	Department string `json:"department"`
	// The datasource profiles of the employee, e.g. `Slack`,`Github`.
	DatasourceProfiles []DatasourceProfile `json:"datasourceProfiles,omitempty"`
	// Info about the employee's team(s)
	Teams []EmployeeTeamInfo `json:"teams,omitempty"`
	// The date when the employee started
	StartDate *types.Date `json:"startDate,omitempty"`
	// If a former employee, the last date of employment.
	EndDate *types.Date `json:"endDate,omitempty"`
	// Short biography or mission statement of the employee.
	Bio *string `json:"bio,omitempty"`
	// She/her, He/his or other pronoun.
	Pronoun *string `json:"pronoun,omitempty"`
	// Other names associated with the employee.
	AlsoKnownAs []string `json:"alsoKnownAs,omitempty"`
	// Link to internal company person profile.
	ProfileURL *string `json:"profileUrl,omitempty"`
	// List of social network profiles.
	SocialNetworks []SocialNetworkDefinition `json:"socialNetworks,omitempty"`
	// The email of the employee's manager
	ManagerEmail *string `json:"managerEmail,omitempty"`
	// **[Advanced]** A unique universal internal identifier for the employee's manager. This is solely used in conjunction with `id`.
	//
	ManagerID *string `json:"managerId,omitempty"`
	// The type of the employee, an enum of `FULL_TIME`, `CONTRACTOR`, `NON_EMPLOYEE`
	Type *string `default:"FULL_TIME" json:"type"`
	// List of unidirectional relationships with other employees. E.g. this employee (`A`) is a CHIEF_OF_STAFF to another employee (`B`); or this employee (`A`) is an EXECUTIVE_ASSISTANT of another employee (`C`). The mapping should be attached to `A`'s profile.
	Relationships []EntityRelationship `json:"relationships,omitempty"`
	// The status of the employee, an enum of `CURRENT`, `FUTURE`, `EX`
	Status *string `default:"CURRENT" json:"status"`
	// List of additional fields with more information about the employee.
	AdditionalFields []AdditionalFieldDefinition `json:"additionalFields,omitempty"`
}

func (e EmployeeInfoDefinition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmployeeInfoDefinition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmployeeInfoDefinition) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EmployeeInfoDefinition) GetFirstName() *string {
	if e == nil {
		return nil
	}
	return e.FirstName
}

func (e *EmployeeInfoDefinition) GetLastName() *string {
	if e == nil {
		return nil
	}
	return e.LastName
}

func (e *EmployeeInfoDefinition) GetPreferredName() *string {
	if e == nil {
		return nil
	}
	return e.PreferredName
}

func (e *EmployeeInfoDefinition) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EmployeeInfoDefinition) GetPhoneNumber() *string {
	if e == nil {
		return nil
	}
	return e.PhoneNumber
}

func (e *EmployeeInfoDefinition) GetLocation() *string {
	if e == nil {
		return nil
	}
	return e.Location
}

func (e *EmployeeInfoDefinition) GetStructuredLocation() *StructuredLocation {
	if e == nil {
		return nil
	}
	return e.StructuredLocation
}

func (e *EmployeeInfoDefinition) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *EmployeeInfoDefinition) GetPhotoURL() *string {
	if e == nil {
		return nil
	}
	return e.PhotoURL
}

func (e *EmployeeInfoDefinition) GetBusinessUnit() *string {
	if e == nil {
		return nil
	}
	return e.BusinessUnit
}

func (e *EmployeeInfoDefinition) GetDepartment() string {
	if e == nil {
		return ""
	}
	return e.Department
}

func (e *EmployeeInfoDefinition) GetDatasourceProfiles() []DatasourceProfile {
	if e == nil {
		return nil
	}
	return e.DatasourceProfiles
}

func (e *EmployeeInfoDefinition) GetTeams() []EmployeeTeamInfo {
	if e == nil {
		return nil
	}
	return e.Teams
}

func (e *EmployeeInfoDefinition) GetStartDate() *types.Date {
	if e == nil {
		return nil
	}
	return e.StartDate
}

func (e *EmployeeInfoDefinition) GetEndDate() *types.Date {
	if e == nil {
		return nil
	}
	return e.EndDate
}

func (e *EmployeeInfoDefinition) GetBio() *string {
	if e == nil {
		return nil
	}
	return e.Bio
}

func (e *EmployeeInfoDefinition) GetPronoun() *string {
	if e == nil {
		return nil
	}
	return e.Pronoun
}

func (e *EmployeeInfoDefinition) GetAlsoKnownAs() []string {
	if e == nil {
		return nil
	}
	return e.AlsoKnownAs
}

func (e *EmployeeInfoDefinition) GetProfileURL() *string {
	if e == nil {
		return nil
	}
	return e.ProfileURL
}

func (e *EmployeeInfoDefinition) GetSocialNetworks() []SocialNetworkDefinition {
	if e == nil {
		return nil
	}
	return e.SocialNetworks
}

func (e *EmployeeInfoDefinition) GetManagerEmail() *string {
	if e == nil {
		return nil
	}
	return e.ManagerEmail
}

func (e *EmployeeInfoDefinition) GetManagerID() *string {
	if e == nil {
		return nil
	}
	return e.ManagerID
}

func (e *EmployeeInfoDefinition) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *EmployeeInfoDefinition) GetRelationships() []EntityRelationship {
	if e == nil {
		return nil
	}
	return e.Relationships
}

func (e *EmployeeInfoDefinition) GetStatus() *string {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *EmployeeInfoDefinition) GetAdditionalFields() []AdditionalFieldDefinition {
	if e == nil {
		return nil
	}
	return e.AdditionalFields
}
