// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EmployeeTeamInfo - Information about which team an employee belongs to
type EmployeeTeamInfo struct {
	// unique identifier for this team
	ID *string `json:"id,omitempty"`
	// Team name
	Name *string `json:"name,omitempty"`
	// Link to internal company team page
	URL *string `json:"url,omitempty"`
}

func (e *EmployeeTeamInfo) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EmployeeTeamInfo) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EmployeeTeamInfo) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}
