// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ExportInfoStatus - The status of the export
type ExportInfoStatus string

const (
	ExportInfoStatusPending   ExportInfoStatus = "PENDING"
	ExportInfoStatusCompleted ExportInfoStatus = "COMPLETED"
	ExportInfoStatusFailed    ExportInfoStatus = "FAILED"
)

func (e ExportInfoStatus) ToPointer() *ExportInfoStatus {
	return &e
}
func (e *ExportInfoStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "FAILED":
		*e = ExportInfoStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExportInfoStatus: %v", v)
	}
}

type ExportInfo struct {
	// Details about the person who created this report/policy.
	CreatedBy *DlpPerson `json:"createdBy,omitempty"`
	// Timestamp at which this export started.
	StartTime *string `json:"startTime,omitempty"`
	// Timestamp at which this export completed.
	EndTime *string `json:"endTime,omitempty"`
	// The ID of the export
	ExportID *string `json:"exportId,omitempty"`
	// The name of the file to export the findings to
	FileName *string           `json:"fileName,omitempty"`
	Filter   *DlpFindingFilter `json:"filter,omitempty"`
	// The status of the export
	Status *ExportInfoStatus `json:"status,omitempty"`
	// The size of the exported file in bytes
	ExportSize *int64 `json:"exportSize,omitempty"`
}

func (e *ExportInfo) GetCreatedBy() *DlpPerson {
	if e == nil {
		return nil
	}
	return e.CreatedBy
}

func (e *ExportInfo) GetStartTime() *string {
	if e == nil {
		return nil
	}
	return e.StartTime
}

func (e *ExportInfo) GetEndTime() *string {
	if e == nil {
		return nil
	}
	return e.EndTime
}

func (e *ExportInfo) GetExportID() *string {
	if e == nil {
		return nil
	}
	return e.ExportID
}

func (e *ExportInfo) GetFileName() *string {
	if e == nil {
		return nil
	}
	return e.FileName
}

func (e *ExportInfo) GetFilter() *DlpFindingFilter {
	if e == nil {
		return nil
	}
	return e.Filter
}

func (e *ExportInfo) GetStatus() *ExportInfoStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ExportInfo) GetExportSize() *int64 {
	if e == nil {
		return nil
	}
	return e.ExportSize
}
