// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type FacetBucketFilter struct {
	// The facet whose buckets should be filtered.
	Facet *string `json:"facet,omitempty"`
	// The per-term prefix that facet buckets should be filtered on.
	Prefix *string `json:"prefix,omitempty"`
}

func (f FacetBucketFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FacetBucketFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FacetBucketFilter) GetFacet() *string {
	if f == nil {
		return nil
	}
	return f.Facet
}

func (f *FacetBucketFilter) GetPrefix() *string {
	if f == nil {
		return nil
	}
	return f.Prefix
}
