// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetChatApplicationResponse struct {
	Application any `json:"application,omitempty"`
}

func (g *GetChatApplicationResponse) GetApplication() any {
	if g == nil {
		return nil
	}
	return g.Application
}
