// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetChatFilesRequest struct {
	// IDs of files to fetch.
	FileIds []string `json:"fileIds"`
}

func (g *GetChatFilesRequest) GetFileIds() []string {
	if g == nil {
		return []string{}
	}
	return g.FileIds
}
