// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetDocPermissionsResponse struct {
	// A list of emails of users who have access to the document. If the document is visible to all Glean users, a list with only a single value of 'VISIBLE_TO_ALL'.
	AllowedUserEmails []string `json:"allowedUserEmails,omitempty"`
}

func (g *GetDocPermissionsResponse) GetAllowedUserEmails() []string {
	if g == nil {
		return nil
	}
	return g.AllowedUserEmails
}
