// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetDocumentVisibilityOverridesResponse struct {
	VisibilityOverrides []DocumentVisibilityOverride `json:"visibilityOverrides,omitempty"`
}

func (g *GetDocumentVisibilityOverridesResponse) GetVisibilityOverrides() []DocumentVisibilityOverride {
	if g == nil {
		return nil
	}
	return g.VisibilityOverrides
}
