// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetDocumentStatusResponse - Describes the response body of the /getdocumentstatus API call
type GetDocumentStatusResponse struct {
	// Upload status, enum of NOT_UPLOADED, UPLOADED, STATUS_UNKNOWN
	UploadStatus *string `json:"uploadStatus,omitempty"`
	// Time of last successful upload, in epoch seconds
	LastUploadedAt *int64 `json:"lastUploadedAt,omitempty"`
	// Indexing status, enum of NOT_INDEXED, INDEXED, STATUS_UNKNOWN
	IndexingStatus *string `json:"indexingStatus,omitempty"`
	// Time of last successful indexing, in epoch seconds
	LastIndexedAt *int64 `json:"lastIndexedAt,omitempty"`
}

func (g *GetDocumentStatusResponse) GetUploadStatus() *string {
	if g == nil {
		return nil
	}
	return g.UploadStatus
}

func (g *GetDocumentStatusResponse) GetLastUploadedAt() *int64 {
	if g == nil {
		return nil
	}
	return g.LastUploadedAt
}

func (g *GetDocumentStatusResponse) GetIndexingStatus() *string {
	if g == nil {
		return nil
	}
	return g.IndexingStatus
}

func (g *GetDocumentStatusResponse) GetLastIndexedAt() *int64 {
	if g == nil {
		return nil
	}
	return g.LastIndexedAt
}
