// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetDocumentsByFacetsResponse struct {
	// The document details, ordered by score.
	Documents []Document `json:"documents,omitempty"`
	// Whether more results are available. Use cursor to retrieve them.
	HasMoreResults *bool `json:"hasMoreResults,omitempty"`
	// Cursor that indicates the start of the next page of results. To be passed in "more" requests for this query.
	Cursor *string `json:"cursor,omitempty"`
}

func (g *GetDocumentsByFacetsResponse) GetDocuments() []Document {
	if g == nil {
		return nil
	}
	return g.Documents
}

func (g *GetDocumentsByFacetsResponse) GetHasMoreResults() *bool {
	if g == nil {
		return nil
	}
	return g.HasMoreResults
}

func (g *GetDocumentsByFacetsResponse) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}
