// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GreenlistUsersRequest - Describes the request body of the /betausers API call
type GreenlistUsersRequest struct {
	// Datasource which needs to be made visible to users specified in the `emails` field.
	Datasource string `json:"datasource"`
	// The emails of the beta users
	Emails []string `json:"emails"`
}

func (g *GreenlistUsersRequest) GetDatasource() string {
	if g == nil {
		return ""
	}
	return g.Datasource
}

func (g *GreenlistUsersRequest) GetEmails() []string {
	if g == nil {
		return []string{}
	}
	return g.Emails
}
