// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GroupType - The type of user group
type GroupType string

const (
	GroupTypeDepartment    GroupType = "DEPARTMENT"
	GroupTypeAll           GroupType = "ALL"
	GroupTypeTeam          GroupType = "TEAM"
	GroupTypeJobTitle      GroupType = "JOB_TITLE"
	GroupTypeRoleType      GroupType = "ROLE_TYPE"
	GroupTypeLocation      GroupType = "LOCATION"
	GroupTypeRegion        GroupType = "REGION"
	GroupTypeExternalGroup GroupType = "EXTERNAL_GROUP"
)

func (e GroupType) ToPointer() *GroupType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GroupType) IsExact() bool {
	if e != nil {
		switch *e {
		case "DEPARTMENT", "ALL", "TEAM", "JOB_TITLE", "ROLE_TYPE", "LOCATION", "REGION", "EXTERNAL_GROUP":
			return true
		}
	}
	return false
}
