// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type Group struct {
	// The type of user group
	Type GroupType `json:"type"`
	// A unique identifier for the group. May be the same as name.
	ID string `json:"id"`
	// Name of the group.
	Name *string `json:"name,omitempty"`
	// Datasource instance if the group belongs to one e.g. external groups.
	DatasourceInstance *string `json:"datasourceInstance,omitempty"`
	// identifier for greenlist provisioning, aka sciokey
	ProvisioningID *string `json:"provisioningId,omitempty"`
}

func (g Group) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Group) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"type", "id"}); err != nil {
		return err
	}
	return nil
}

func (g *Group) GetType() GroupType {
	if g == nil {
		return GroupType("")
	}
	return g.Type
}

func (g *Group) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *Group) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *Group) GetDatasourceInstance() *string {
	if g == nil {
		return nil
	}
	return g.DatasourceInstance
}

func (g *Group) GetProvisioningID() *string {
	if g == nil {
		return nil
	}
	return g.ProvisioningID
}
