// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Hotword struct {
	Regex     *string           `json:"regex,omitempty"`
	Proximity *HotwordProximity `json:"proximity,omitempty"`
}

func (h *Hotword) GetRegex() *string {
	if h == nil {
		return nil
	}
	return h.Regex
}

func (h *Hotword) GetProximity() *HotwordProximity {
	if h == nil {
		return nil
	}
	return h.Proximity
}
