// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IndexDocumentRequest - Describes the request body of the /indexdocument API call
type IndexDocumentRequest struct {
	// Version number for document for optimistic concurrency control. If absent or 0 then no version checks are done.
	Version *int64 `json:"version,omitempty"`
	// Indexable document structure
	Document DocumentDefinition `json:"document"`
}

func (i *IndexDocumentRequest) GetVersion() *int64 {
	if i == nil {
		return nil
	}
	return i.Version
}

func (i *IndexDocumentRequest) GetDocument() DocumentDefinition {
	if i == nil {
		return DocumentDefinition{}
	}
	return i.Document
}
