// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IndexGroupRequest - Describes the request body of the /indexgroup API call
type IndexGroupRequest struct {
	// Version number for document for optimistic concurrency control. If absent or 0 then no version checks are done.
	Version *int64 `json:"version,omitempty"`
	// The datasource for which the group is added
	Datasource string `json:"datasource"`
	// describes a group in the datasource
	Group DatasourceGroupDefinition `json:"group"`
}

func (i *IndexGroupRequest) GetVersion() *int64 {
	if i == nil {
		return nil
	}
	return i.Version
}

func (i *IndexGroupRequest) GetDatasource() string {
	if i == nil {
		return ""
	}
	return i.Datasource
}

func (i *IndexGroupRequest) GetGroup() DatasourceGroupDefinition {
	if i == nil {
		return DatasourceGroupDefinition{}
	}
	return i.Group
}
