// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InsightsAgentsRequestOptions struct {
	// IDs of the Agents for which Insights should be returned. An empty array signifies all.
	AgentIds []string `json:"agentIds,omitempty"`
}

func (i *InsightsAgentsRequestOptions) GetAgentIds() []string {
	if i == nil {
		return nil
	}
	return i.AgentIds
}
