// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InsightsSearchSummary struct {
	// Number of current Monthly Active Users, in the specified departments.
	MonthlyActiveUsers *int64 `json:"monthlyActiveUsers,omitempty"`
	// Number of current Weekly Active Users, in the specified departments.
	WeeklyActiveUsers *int64 `json:"weeklyActiveUsers,omitempty"`
	// Total number of searches by users over the specified time period.
	NumSearches *int64 `json:"numSearches,omitempty"`
	// Total number of distinct users who searched over the specified time period.
	NumSearchUsers *int64 `json:"numSearchUsers,omitempty"`
}

func (i *InsightsSearchSummary) GetMonthlyActiveUsers() *int64 {
	if i == nil {
		return nil
	}
	return i.MonthlyActiveUsers
}

func (i *InsightsSearchSummary) GetWeeklyActiveUsers() *int64 {
	if i == nil {
		return nil
	}
	return i.WeeklyActiveUsers
}

func (i *InsightsSearchSummary) GetNumSearches() *int64 {
	if i == nil {
		return nil
	}
	return i.NumSearches
}

func (i *InsightsSearchSummary) GetNumSearchUsers() *int64 {
	if i == nil {
		return nil
	}
	return i.NumSearchUsers
}
