// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InsightsResponse struct {
	GleanAssist       *GleanAssistInsightsResponse `json:"gleanAssist,omitempty"`
	OverviewResponse  *InsightsOverviewResponse    `json:"overviewResponse,omitempty"`
	AssistantResponse *AssistantInsightsResponse   `json:"assistantResponse,omitempty"`
	AgentsResponse    *AgentsInsightsV2Response    `json:"agentsResponse,omitempty"`
}

func (i *InsightsResponse) GetGleanAssist() *GleanAssistInsightsResponse {
	if i == nil {
		return nil
	}
	return i.GleanAssist
}

func (i *InsightsResponse) GetOverviewResponse() *InsightsOverviewResponse {
	if i == nil {
		return nil
	}
	return i.OverviewResponse
}

func (i *InsightsResponse) GetAssistantResponse() *AssistantInsightsResponse {
	if i == nil {
		return nil
	}
	return i.AssistantResponse
}

func (i *InsightsResponse) GetAgentsResponse() *AgentsInsightsV2Response {
	if i == nil {
		return nil
	}
	return i.AgentsResponse
}
