// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InsightsOverviewResponse struct {
	// Number of current Monthly Active Users, in the specified departments.
	MonthlyActiveUsers *int64 `json:"monthlyActiveUsers,omitempty"`
	// Number of current Weekly Active Users, in the specified departments.
	WeeklyActiveUsers *int64 `json:"weeklyActiveUsers,omitempty"`
	// Department name(s).
	Departments []string `json:"departments,omitempty"`
	// Number of current employees in the specified departments, according to the Org Chart.
	EmployeeCount *int64 `json:"employeeCount,omitempty"`
	// Number of current signed up employees in the specified departments, according to the Org Chart.
	TotalSignups     *int64                 `json:"totalSignups,omitempty"`
	SearchSummary    *InsightsSearchSummary `json:"searchSummary,omitempty"`
	ChatSummary      *InsightsChatSummary   `json:"chatSummary,omitempty"`
	ExtensionSummary *CurrentActiveUsers    `json:"extensionSummary,omitempty"`
	UgcSummary       *CurrentActiveUsers    `json:"ugcSummary,omitempty"`
	// Unix timestamp of the last update for the insights data in the response.
	LastUpdatedTs *int64 `json:"lastUpdatedTs,omitempty"`
	// Search session satisfaction rate, over the specified time period in the specified departments.
	SearchSessionSatisfaction   *float32          `json:"searchSessionSatisfaction,omitempty"`
	MonthlyActiveUserTimeseries *LabeledCountInfo `json:"monthlyActiveUserTimeseries,omitempty"`
	WeeklyActiveUserTimeseries  *LabeledCountInfo `json:"weeklyActiveUserTimeseries,omitempty"`
	DailyActiveUserTimeseries   *LabeledCountInfo `json:"dailyActiveUserTimeseries,omitempty"`
	// Counts of search result clicks, by datasource, over the specified time period in the specified departments.
	SearchDatasourceCounts map[string]int64 `json:"searchDatasourceCounts,omitempty"`
	// Counts of cited documents in chat, by datasource, over the specified time period in the specified departments.
	ChatDatasourceCounts map[string]int64 `json:"chatDatasourceCounts,omitempty"`
	// Per-user insights, over the specified time period in the specified departments. All current users in the organization who have signed into Glean at least once are included.
	PerUserInsights []PerUserInsight `json:"perUserInsights,omitempty"`
}

func (i *InsightsOverviewResponse) GetMonthlyActiveUsers() *int64 {
	if i == nil {
		return nil
	}
	return i.MonthlyActiveUsers
}

func (i *InsightsOverviewResponse) GetWeeklyActiveUsers() *int64 {
	if i == nil {
		return nil
	}
	return i.WeeklyActiveUsers
}

func (i *InsightsOverviewResponse) GetDepartments() []string {
	if i == nil {
		return nil
	}
	return i.Departments
}

func (i *InsightsOverviewResponse) GetEmployeeCount() *int64 {
	if i == nil {
		return nil
	}
	return i.EmployeeCount
}

func (i *InsightsOverviewResponse) GetTotalSignups() *int64 {
	if i == nil {
		return nil
	}
	return i.TotalSignups
}

func (i *InsightsOverviewResponse) GetSearchSummary() *InsightsSearchSummary {
	if i == nil {
		return nil
	}
	return i.SearchSummary
}

func (i *InsightsOverviewResponse) GetChatSummary() *InsightsChatSummary {
	if i == nil {
		return nil
	}
	return i.ChatSummary
}

func (i *InsightsOverviewResponse) GetExtensionSummary() *CurrentActiveUsers {
	if i == nil {
		return nil
	}
	return i.ExtensionSummary
}

func (i *InsightsOverviewResponse) GetUgcSummary() *CurrentActiveUsers {
	if i == nil {
		return nil
	}
	return i.UgcSummary
}

func (i *InsightsOverviewResponse) GetLastUpdatedTs() *int64 {
	if i == nil {
		return nil
	}
	return i.LastUpdatedTs
}

func (i *InsightsOverviewResponse) GetSearchSessionSatisfaction() *float32 {
	if i == nil {
		return nil
	}
	return i.SearchSessionSatisfaction
}

func (i *InsightsOverviewResponse) GetMonthlyActiveUserTimeseries() *LabeledCountInfo {
	if i == nil {
		return nil
	}
	return i.MonthlyActiveUserTimeseries
}

func (i *InsightsOverviewResponse) GetWeeklyActiveUserTimeseries() *LabeledCountInfo {
	if i == nil {
		return nil
	}
	return i.WeeklyActiveUserTimeseries
}

func (i *InsightsOverviewResponse) GetDailyActiveUserTimeseries() *LabeledCountInfo {
	if i == nil {
		return nil
	}
	return i.DailyActiveUserTimeseries
}

func (i *InsightsOverviewResponse) GetSearchDatasourceCounts() map[string]int64 {
	if i == nil {
		return nil
	}
	return i.SearchDatasourceCounts
}

func (i *InsightsOverviewResponse) GetChatDatasourceCounts() map[string]int64 {
	if i == nil {
		return nil
	}
	return i.ChatDatasourceCounts
}

func (i *InsightsOverviewResponse) GetPerUserInsights() []PerUserInsight {
	if i == nil {
		return nil
	}
	return i.PerUserInsights
}
