// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InvalidOperatorValueError struct {
	// The operator key that has an invalid value.
	Key *string `json:"key,omitempty"`
	// The invalid operator value.
	Value *string `json:"value,omitempty"`
}

func (i *InvalidOperatorValueError) GetKey() *string {
	if i == nil {
		return nil
	}
	return i.Key
}

func (i *InvalidOperatorValueError) GetValue() *string {
	if i == nil {
		return nil
	}
	return i.Value
}
