// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListDlpReportsResponse struct {
	Reports []DlpReport `json:"reports,omitempty"`
}

func (l *ListDlpReportsResponse) GetReports() []DlpReport {
	if l == nil {
		return nil
	}
	return l.Reports
}
