// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ListShortcutsPaginatedRequestIncludeField string

const (
	ListShortcutsPaginatedRequestIncludeFieldFacets        ListShortcutsPaginatedRequestIncludeField = "FACETS"
	ListShortcutsPaginatedRequestIncludeFieldPeopleDetails ListShortcutsPaginatedRequestIncludeField = "PEOPLE_DETAILS"
)

func (e ListShortcutsPaginatedRequestIncludeField) ToPointer() *ListShortcutsPaginatedRequestIncludeField {
	return &e
}
func (e *ListShortcutsPaginatedRequestIncludeField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FACETS":
		fallthrough
	case "PEOPLE_DETAILS":
		*e = ListShortcutsPaginatedRequestIncludeField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListShortcutsPaginatedRequestIncludeField: %v", v)
	}
}

type ListShortcutsPaginatedRequest struct {
	// Array of fields/data to be included in response that are not included by default
	IncludeFields []ListShortcutsPaginatedRequestIncludeField `json:"includeFields,omitempty"`
	PageSize      int64                                       `json:"pageSize"`
	// A token specifying the position in the overall results to start at. Received from the endpoint and iterated back. Currently being used as page no (as we implement offset pagination)
	Cursor *string `json:"cursor,omitempty"`
	// A list of filters for the query. An AND is assumed between different filters. We support filters on Go Link name, author, department and type.
	Filters []FacetFilter `json:"filters,omitempty"`
	Sort    *SortOptions  `json:"sort,omitempty"`
	// Search query that should be a substring in atleast one of the fields (alias , inputAlias, destinationUrl, description). Empty query does not filter shortcuts.
	Query *string `json:"query,omitempty"`
}

func (l *ListShortcutsPaginatedRequest) GetIncludeFields() []ListShortcutsPaginatedRequestIncludeField {
	if l == nil {
		return nil
	}
	return l.IncludeFields
}

func (l *ListShortcutsPaginatedRequest) GetPageSize() int64 {
	if l == nil {
		return 0
	}
	return l.PageSize
}

func (l *ListShortcutsPaginatedRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListShortcutsPaginatedRequest) GetFilters() []FacetFilter {
	if l == nil {
		return nil
	}
	return l.Filters
}

func (l *ListShortcutsPaginatedRequest) GetSort() *SortOptions {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListShortcutsPaginatedRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}
