// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListCollectionsResponse struct {
	// List of all Collections, no Collection items are fetched.
	Collections []Collection `json:"collections"`
}

func (l *ListCollectionsResponse) GetCollections() []Collection {
	if l == nil {
		return []Collection{}
	}
	return l.Collections
}
