// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAnswersResponse struct {
	// List of answers with tracking tokens.
	AnswerResults []AnswerResult `json:"answerResults"`
}

func (l *ListAnswersResponse) GetAnswerResults() []AnswerResult {
	if l == nil {
		return []AnswerResult{}
	}
	return l.AnswerResults
}
