// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MessagesResponse struct {
	// Whether there are more results for client to continue requesting.
	HasMore        bool            `json:"hasMore"`
	SearchResponse *SearchResponse `json:"searchResponse,omitempty"`
	RootMessage    *SearchResult   `json:"rootMessage,omitempty"`
}

func (m *MessagesResponse) GetHasMore() bool {
	if m == nil {
		return false
	}
	return m.HasMore
}

func (m *MessagesResponse) GetSearchResponse() *SearchResponse {
	if m == nil {
		return nil
	}
	return m.SearchResponse
}

func (m *MessagesResponse) GetRootMessage() *SearchResult {
	if m == nil {
		return nil
	}
	return m.RootMessage
}
