// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DocCategory - The document category of this object type.
type DocCategory string

const (
	DocCategoryUncategorized        DocCategory = "UNCATEGORIZED"
	DocCategoryTickets              DocCategory = "TICKETS"
	DocCategoryCrm                  DocCategory = "CRM"
	DocCategoryPublishedContent     DocCategory = "PUBLISHED_CONTENT"
	DocCategoryCollaborativeContent DocCategory = "COLLABORATIVE_CONTENT"
	DocCategoryQuestionAnswer       DocCategory = "QUESTION_ANSWER"
	DocCategoryMessaging            DocCategory = "MESSAGING"
	DocCategoryCodeRepository       DocCategory = "CODE_REPOSITORY"
	DocCategoryChangeManagement     DocCategory = "CHANGE_MANAGEMENT"
	DocCategoryPeople               DocCategory = "PEOPLE"
	DocCategoryEmail                DocCategory = "EMAIL"
	DocCategorySso                  DocCategory = "SSO"
	DocCategoryAts                  DocCategory = "ATS"
	DocCategoryKnowledgeHub         DocCategory = "KNOWLEDGE_HUB"
	DocCategoryExternalShortcut     DocCategory = "EXTERNAL_SHORTCUT"
	DocCategoryEntity               DocCategory = "ENTITY"
	DocCategoryCalendar             DocCategory = "CALENDAR"
	DocCategoryAgents               DocCategory = "AGENTS"
)

func (e DocCategory) ToPointer() *DocCategory {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DocCategory) IsExact() bool {
	if e != nil {
		switch *e {
		case "UNCATEGORIZED", "TICKETS", "CRM", "PUBLISHED_CONTENT", "COLLABORATIVE_CONTENT", "QUESTION_ANSWER", "MESSAGING", "CODE_REPOSITORY", "CHANGE_MANAGEMENT", "PEOPLE", "EMAIL", "SSO", "ATS", "KNOWLEDGE_HUB", "EXTERNAL_SHORTCUT", "ENTITY", "CALENDAR", "AGENTS":
			return true
		}
	}
	return false
}

// ObjectDefinition - The definition for an `DocumentMetadata.objectType` within a datasource.
type ObjectDefinition struct {
	// Unique identifier for this `DocumentMetadata.objectType`. If omitted, this definition is used as a default for all unmatched `DocumentMetadata.objectType`s in this datasource.
	Name *string `json:"name,omitempty"`
	// The user-friendly name of the object for display.
	DisplayLabel *string `json:"displayLabel,omitempty"`
	// The document category of this object type.
	DocCategory         *DocCategory         `json:"docCategory,omitempty"`
	PropertyDefinitions []PropertyDefinition `json:"propertyDefinitions,omitempty"`
	// A list of `PropertyGroup`s belonging to this object type, which will group properties to be displayed together in the UI.
	PropertyGroups []PropertyGroup `json:"propertyGroups,omitempty"`
	// Whether or not the object is summarizable
	Summarizable *bool `json:"summarizable,omitempty"`
}

func (o *ObjectDefinition) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObjectDefinition) GetDisplayLabel() *string {
	if o == nil {
		return nil
	}
	return o.DisplayLabel
}

func (o *ObjectDefinition) GetDocCategory() *DocCategory {
	if o == nil {
		return nil
	}
	return o.DocCategory
}

func (o *ObjectDefinition) GetPropertyDefinitions() []PropertyDefinition {
	if o == nil {
		return nil
	}
	return o.PropertyDefinitions
}

func (o *ObjectDefinition) GetPropertyGroups() []PropertyGroup {
	if o == nil {
		return nil
	}
	return o.PropertyGroups
}

func (o *ObjectDefinition) GetSummarizable() *bool {
	if o == nil {
		return nil
	}
	return o.Summarizable
}
