// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PerAgentInsight struct {
	// Agent ID
	AgentID *string `json:"agentId,omitempty"`
	// Agent name
	AgentName *string `json:"agentName,omitempty"`
	// Defines how to render an icon
	Icon *IconConfig `json:"icon,omitempty"`
	// Total number of users for this agent over the specified time period.
	UserCount *int64 `json:"userCount,omitempty"`
	// Total number of runs for this agent over the specified time period.
	RunCount *int64 `json:"runCount,omitempty"`
}

func (p *PerAgentInsight) GetAgentID() *string {
	if p == nil {
		return nil
	}
	return p.AgentID
}

func (p *PerAgentInsight) GetAgentName() *string {
	if p == nil {
		return nil
	}
	return p.AgentName
}

func (p *PerAgentInsight) GetIcon() *IconConfig {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PerAgentInsight) GetUserCount() *int64 {
	if p == nil {
		return nil
	}
	return p.UserCount
}

func (p *PerAgentInsight) GetRunCount() *int64 {
	if p == nil {
		return nil
	}
	return p.RunCount
}
