// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type Period struct {
	// DEPRECATED - The number of days from now in the past to define upper boundary of time period.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	MinDaysFromNow *int64 `json:"minDaysFromNow,omitempty"`
	// DEPRECATED - The number of days from now in the past to define lower boundary of time period.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	MaxDaysFromNow *int64     `json:"maxDaysFromNow,omitempty"`
	Start          *TimePoint `json:"start,omitempty"`
	End            *TimePoint `json:"end,omitempty"`
}

func (p Period) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Period) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Period) GetMinDaysFromNow() *int64 {
	if p == nil {
		return nil
	}
	return p.MinDaysFromNow
}

func (p *Period) GetMaxDaysFromNow() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxDaysFromNow
}

func (p *Period) GetStart() *TimePoint {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *Period) GetEnd() *TimePoint {
	if p == nil {
		return nil
	}
	return p.End
}
