// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PersonDistance struct {
	// The display name.
	Name string `json:"name"`
	// An opaque identifier that can be used to request metadata for a Person.
	ObfuscatedID string `json:"obfuscatedId"`
	// Distance to person, refer to PeopleDistance pipeline on interpretation of the value.
	Distance float32 `json:"distance"`
}

func (p PersonDistance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonDistance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersonDistance) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PersonDistance) GetObfuscatedID() string {
	if p == nil {
		return ""
	}
	return p.ObfuscatedID
}

func (p *PersonDistance) GetDistance() float32 {
	if p == nil {
		return 0.0
	}
	return p.Distance
}
