// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PerUserInsight struct {
	Person *Person `json:"person,omitempty"`
	// Total number of searches by this user over the specified time period.
	NumSearches *int64 `json:"numSearches,omitempty"`
	// Total number of chats by this user over the specified time period.
	NumChats *int64 `json:"numChats,omitempty"`
	// Total number of active sessions by this user in a Glean client over the specified time period.
	NumActiveSessions *int64 `json:"numActiveSessions,omitempty"`
	// Total number of Gleanbot responses marked useful by this user over the specified time period.
	NumGleanbotUsefulResponses *int64 `json:"numGleanbotUsefulResponses,omitempty"`
	// Total number of days this user was an Active User over the specified time period.
	NumDaysActive *int64 `json:"numDaysActive,omitempty"`
}

func (p *PerUserInsight) GetPerson() *Person {
	if p == nil {
		return nil
	}
	return p.Person
}

func (p *PerUserInsight) GetNumSearches() *int64 {
	if p == nil {
		return nil
	}
	return p.NumSearches
}

func (p *PerUserInsight) GetNumChats() *int64 {
	if p == nil {
		return nil
	}
	return p.NumChats
}

func (p *PerUserInsight) GetNumActiveSessions() *int64 {
	if p == nil {
		return nil
	}
	return p.NumActiveSessions
}

func (p *PerUserInsight) GetNumGleanbotUsefulResponses() *int64 {
	if p == nil {
		return nil
	}
	return p.NumGleanbotUsefulResponses
}

func (p *PerUserInsight) GetNumDaysActive() *int64 {
	if p == nil {
		return nil
	}
	return p.NumDaysActive
}
