// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PropertyGroup - A grouping for multiple PropertyDefinition. Grouped properties will be displayed together in the UI.
type PropertyGroup struct {
	// The unique identifier of the group.
	Name *string `json:"name,omitempty"`
	// The user-friendly group label to display.
	DisplayLabel *string `json:"displayLabel,omitempty"`
}

func (p *PropertyGroup) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PropertyGroup) GetDisplayLabel() *string {
	if p == nil {
		return nil
	}
	return p.DisplayLabel
}
