// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Scope string

const (
	ScopeAppCard                Scope = "APP_CARD"
	ScopeAutocompleteExactMatch Scope = "AUTOCOMPLETE_EXACT_MATCH"
	ScopeAutocompleteFuzzyMatch Scope = "AUTOCOMPLETE_FUZZY_MATCH"
	ScopeAutocompleteZeroQuery  Scope = "AUTOCOMPLETE_ZERO_QUERY"
	ScopeNewTabPage             Scope = "NEW_TAB_PAGE"
)

func (e Scope) ToPointer() *Scope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Scope) IsExact() bool {
	if e != nil {
		switch *e {
		case "APP_CARD", "AUTOCOMPLETE_EXACT_MATCH", "AUTOCOMPLETE_FUZZY_MATCH", "AUTOCOMPLETE_ZERO_QUERY", "NEW_TAB_PAGE":
			return true
		}
	}
	return false
}

// Quicklink - An action for a specific datasource that will show up in autocomplete and app card, e.g. "Create new issue" for jira.
type Quicklink struct {
	// Full action name. Used in autocomplete.
	Name *string `json:"name,omitempty"`
	// Shortened name. Used in app cards.
	ShortName *string `json:"shortName,omitempty"`
	// The URL of the action.
	URL *string `json:"url,omitempty"`
	// Defines how to render an icon
	IconConfig *IconConfig `json:"iconConfig,omitempty"`
	// Unique identifier of this quicklink
	ID *string `json:"id,omitempty"`
	// The scopes for which this quicklink is applicable
	Scopes []Scope `json:"scopes,omitempty"`
}

func (q *Quicklink) GetName() *string {
	if q == nil {
		return nil
	}
	return q.Name
}

func (q *Quicklink) GetShortName() *string {
	if q == nil {
		return nil
	}
	return q.ShortName
}

func (q *Quicklink) GetURL() *string {
	if q == nil {
		return nil
	}
	return q.URL
}

func (q *Quicklink) GetIconConfig() *IconConfig {
	if q == nil {
		return nil
	}
	return q.IconConfig
}

func (q *Quicklink) GetID() *string {
	if q == nil {
		return nil
	}
	return q.ID
}

func (q *Quicklink) GetScopes() []Scope {
	if q == nil {
		return nil
	}
	return q.Scopes
}
