// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ReferenceRange - Each text range from the response can correspond to an array of snippets from the citation source.
type ReferenceRange struct {
	// A subsection of a given string to which some special formatting should be applied.
	TextRange *TextRange            `json:"textRange,omitempty"`
	Snippets  []SearchResultSnippet `json:"snippets,omitempty"`
}

func (r *ReferenceRange) GetTextRange() *TextRange {
	if r == nil {
		return nil
	}
	return r.TextRange
}

func (r *ReferenceRange) GetSnippets() []SearchResultSnippet {
	if r == nil {
		return nil
	}
	return r.Snippets
}
