// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type RelatedQuestion struct {
	// The text of the related question
	Question *string `json:"question,omitempty"`
	// The answer for the related question
	Answer *string `json:"answer,omitempty"`
	// Subsections of the answer string to which some special formatting should be applied (eg. bold)
	Ranges []TextRange `json:"ranges,omitempty"`
}

func (r RelatedQuestion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelatedQuestion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RelatedQuestion) GetQuestion() *string {
	if r == nil {
		return nil
	}
	return r.Question
}

func (r *RelatedQuestion) GetAnswer() *string {
	if r == nil {
		return nil
	}
	return r.Answer
}

func (r *RelatedQuestion) GetRanges() []TextRange {
	if r == nil {
		return nil
	}
	return r.Ranges
}
