// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// RelatedObjectMetadata - Some metadata of the object which can be displayed, while not having the actual object.
type RelatedObjectMetadata struct {
	// Placeholder name of the object, not the relationship.
	Name *string `json:"name,omitempty"`
}

func (r RelatedObjectMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelatedObjectMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RelatedObjectMetadata) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

type RelatedObject struct {
	// The ID of the related object
	ID string `json:"id"`
	// Some metadata of the object which can be displayed, while not having the actual object.
	Metadata *RelatedObjectMetadata `json:"metadata,omitempty"`
}

func (r RelatedObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelatedObject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (r *RelatedObject) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RelatedObject) GetMetadata() *RelatedObjectMetadata {
	if r == nil {
		return nil
	}
	return r.Metadata
}
