// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReportStatusResponseStatus string

const (
	ReportStatusResponseStatusPending    ReportStatusResponseStatus = "PENDING"
	ReportStatusResponseStatusSuccess    ReportStatusResponseStatus = "SUCCESS"
	ReportStatusResponseStatusFailure    ReportStatusResponseStatus = "FAILURE"
	ReportStatusResponseStatusCancelled  ReportStatusResponseStatus = "CANCELLED"
	ReportStatusResponseStatusCancelling ReportStatusResponseStatus = "CANCELLING"
	ReportStatusResponseStatusActive     ReportStatusResponseStatus = "ACTIVE"
)

func (e ReportStatusResponseStatus) ToPointer() *ReportStatusResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ReportStatusResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "PENDING", "SUCCESS", "FAILURE", "CANCELLED", "CANCELLING", "ACTIVE":
			return true
		}
	}
	return false
}

type ReportStatusResponse struct {
	Status *ReportStatusResponseStatus `json:"status,omitempty"`
	// The timestamp at which the report's run/scan began.
	StartTime *string `json:"startTime,omitempty"`
}

func (r *ReportStatusResponse) GetStatus() *ReportStatusResponseStatus {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ReportStatusResponse) GetStartTime() *string {
	if r == nil {
		return nil
	}
	return r.StartTime
}
