// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResultsResponse struct {
	// A token that should be passed for additional requests related to this request (such as more results requests).
	TrackingToken      *string            `json:"trackingToken,omitempty"`
	SessionInfo        *SessionInfo       `json:"sessionInfo,omitempty"`
	Results            []SearchResult     `json:"results,omitempty"`
	StructuredResults  []StructuredResult `json:"structuredResults,omitempty"`
	GeneratedQnaResult *GeneratedQna      `json:"generatedQnaResult,omitempty"`
	GleanDataError     *GleanDataError    `json:"errorInfo,omitempty"`
	// A platform-generated request ID to correlate backend logs.
	RequestID *string `json:"requestID,omitempty"`
	// Time in milliseconds the backend took to respond to the request.
	BackendTimeMillis *int64 `json:"backendTimeMillis,omitempty"`
}

func (r *ResultsResponse) GetTrackingToken() *string {
	if r == nil {
		return nil
	}
	return r.TrackingToken
}

func (r *ResultsResponse) GetSessionInfo() *SessionInfo {
	if r == nil {
		return nil
	}
	return r.SessionInfo
}

func (r *ResultsResponse) GetResults() []SearchResult {
	if r == nil {
		return nil
	}
	return r.Results
}

func (r *ResultsResponse) GetStructuredResults() []StructuredResult {
	if r == nil {
		return nil
	}
	return r.StructuredResults
}

func (r *ResultsResponse) GetGeneratedQnaResult() *GeneratedQna {
	if r == nil {
		return nil
	}
	return r.GeneratedQnaResult
}

func (r *ResultsResponse) GetGleanDataError() *GleanDataError {
	if r == nil {
		return nil
	}
	return r.GleanDataError
}

func (r *ResultsResponse) GetRequestID() *string {
	if r == nil {
		return nil
	}
	return r.RequestID
}

func (r *ResultsResponse) GetBackendTimeMillis() *int64 {
	if r == nil {
		return nil
	}
	return r.BackendTimeMillis
}
