// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type SearchResult struct {
	// An array of entities in the work graph retrieved via a data request.
	StructuredResults []StructuredResult `json:"structuredResults,omitempty"`
	// An opaque token that represents this particular result in this particular query. To be used for /feedback reporting.
	TrackingToken *string   `json:"trackingToken,omitempty"`
	Document      *Document `json:"document,omitempty"`
	Title         *string   `json:"title,omitempty"`
	URL           string    `json:"url"`
	// A deep link, if available, into the datasource's native application for the user's platform (e.g. slack://...).
	NativeAppURL *string `json:"nativeAppUrl,omitempty"`
	// Text content from the result document which contains search query terms, if available.
	Snippets []SearchResultSnippet `json:"snippets,omitempty"`
	// The full body text of the result if not already contained in the snippets. Only populated for conversation results (e.g. results from a messaging app such as Slack).
	FullText *string `json:"fullText,omitempty"`
	// The full body text of the result if not already contained in the snippets; each item in the array represents a separate line in the original text. Only populated for conversation results (e.g. results from a messaging app such as Slack).
	FullTextList []string `json:"fullTextList,omitempty"`
	// A list of results related to this search result. Eg. for conversation results it contains individual messages from the conversation document which will be shown on SERP.
	RelatedResults []RelatedDocuments `json:"relatedResults,omitempty"`
	// A list of results that should be displayed as associated with this result.
	ClusteredResults []SearchResult `json:"clusteredResults,omitempty"`
	// A list of results that should be displayed as associated with this result.
	AllClusteredResults []ClusterGroup `json:"allClusteredResults,omitempty"`
	// The total number of attachments.
	AttachmentCount *int64 `json:"attachmentCount,omitempty"`
	// A (potentially partial) list of results representing documents attached to the main result document.
	Attachments []SearchResult `json:"attachments,omitempty"`
	// A list of results that should be displayed as backlinks of this result in reverse chronological order.
	BacklinkResults []SearchResult `json:"backlinkResults,omitempty"`
	// The reason for inclusion of clusteredResults.
	ClusterType            *ClusterTypeEnum     `json:"clusterType,omitempty"`
	MustIncludeSuggestions *QuerySuggestionList `json:"mustIncludeSuggestions,omitempty"`
	QuerySuggestion        *QuerySuggestion     `json:"querySuggestion,omitempty"`
	// The level of visual distinction that should be given to a result.
	//
	Prominence *SearchResultProminenceEnum `json:"prominence,omitempty"`
	// Additional context for the relationship between the result and the document it's attached to.
	AttachmentContext *string `json:"attachmentContext,omitempty"`
	// A list of pins associated with this search result.
	Pins []PinDocument `json:"pins,omitempty"`
}

func (s SearchResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (s *SearchResult) GetStructuredResults() []StructuredResult {
	if s == nil {
		return nil
	}
	return s.StructuredResults
}

func (s *SearchResult) GetTrackingToken() *string {
	if s == nil {
		return nil
	}
	return s.TrackingToken
}

func (s *SearchResult) GetDocument() *Document {
	if s == nil {
		return nil
	}
	return s.Document
}

func (s *SearchResult) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *SearchResult) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SearchResult) GetNativeAppURL() *string {
	if s == nil {
		return nil
	}
	return s.NativeAppURL
}

func (s *SearchResult) GetSnippets() []SearchResultSnippet {
	if s == nil {
		return nil
	}
	return s.Snippets
}

func (s *SearchResult) GetFullText() *string {
	if s == nil {
		return nil
	}
	return s.FullText
}

func (s *SearchResult) GetFullTextList() []string {
	if s == nil {
		return nil
	}
	return s.FullTextList
}

func (s *SearchResult) GetRelatedResults() []RelatedDocuments {
	if s == nil {
		return nil
	}
	return s.RelatedResults
}

func (s *SearchResult) GetClusteredResults() []SearchResult {
	if s == nil {
		return nil
	}
	return s.ClusteredResults
}

func (s *SearchResult) GetAllClusteredResults() []ClusterGroup {
	if s == nil {
		return nil
	}
	return s.AllClusteredResults
}

func (s *SearchResult) GetAttachmentCount() *int64 {
	if s == nil {
		return nil
	}
	return s.AttachmentCount
}

func (s *SearchResult) GetAttachments() []SearchResult {
	if s == nil {
		return nil
	}
	return s.Attachments
}

func (s *SearchResult) GetBacklinkResults() []SearchResult {
	if s == nil {
		return nil
	}
	return s.BacklinkResults
}

func (s *SearchResult) GetClusterType() *ClusterTypeEnum {
	if s == nil {
		return nil
	}
	return s.ClusterType
}

func (s *SearchResult) GetMustIncludeSuggestions() *QuerySuggestionList {
	if s == nil {
		return nil
	}
	return s.MustIncludeSuggestions
}

func (s *SearchResult) GetQuerySuggestion() *QuerySuggestion {
	if s == nil {
		return nil
	}
	return s.QuerySuggestion
}

func (s *SearchResult) GetProminence() *SearchResultProminenceEnum {
	if s == nil {
		return nil
	}
	return s.Prominence
}

func (s *SearchResult) GetAttachmentContext() *string {
	if s == nil {
		return nil
	}
	return s.AttachmentContext
}

func (s *SearchResult) GetPins() []PinDocument {
	if s == nil {
		return nil
	}
	return s.Pins
}
