// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	ActAsBearerToken *string `security:"scheme,type=apiKey,subtype=header,name=Authorization,env=glean_act_as_bearer_token"`
	CookieAuth       *string `security:"scheme,type=apiKey,subtype=header,name=Authorization,env=glean_cookie_auth"`
}

func (o *Security) GetActAsBearerToken() *string {
	if o == nil {
		return nil
	}
	return o.ActAsBearerToken
}

func (o *Security) GetCookieAuth() *string {
	if o == nil {
		return nil
	}
	return o.CookieAuth
}
