// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SeenFeedbackInfo struct {
	// The confidence of the user seeing the object is high because they explicitly interacted with it e.g. answer impression in SERP with additional user interaction.
	IsExplicit *bool `json:"isExplicit,omitempty"`
}

func (s *SeenFeedbackInfo) GetIsExplicit() *bool {
	if s == nil {
		return nil
	}
	return s.IsExplicit
}
