// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SensitiveExpression struct {
	// Sensitive word, phrase, or regular expression.
	Expression *string `json:"expression,omitempty"`
	// Zero to three proximate regular expressions necessary to consider an expression as sensitive content.
	Hotwords []Hotword `json:"hotwords,omitempty"`
}

func (o *SensitiveExpression) GetExpression() *string {
	if o == nil {
		return nil
	}
	return o.Expression
}

func (o *SensitiveExpression) GetHotwords() []Hotword {
	if o == nil {
		return nil
	}
	return o.Hotwords
}
