// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SensitiveContentOptions - Options for defining sensitive content within scanned documents.
type SensitiveContentOptions struct {
	// Predefined categories of terms to consider as sensitive content. See https://cloud.google.com/dlp/docs/infotypes-reference for available types.
	SensitiveInfoTypes []SensitiveInfoType `json:"sensitiveInfoTypes,omitempty"`
	// list of words and phrases to consider as sensitive content
	SensitiveTerms []SensitiveExpression `json:"sensitiveTerms,omitempty"`
	// list of regular expressions to consider as sensitive content
	SensitiveRegexes []SensitiveExpression `json:"sensitiveRegexes,omitempty"`
}

func (s *SensitiveContentOptions) GetSensitiveInfoTypes() []SensitiveInfoType {
	if s == nil {
		return nil
	}
	return s.SensitiveInfoTypes
}

func (s *SensitiveContentOptions) GetSensitiveTerms() []SensitiveExpression {
	if s == nil {
		return nil
	}
	return s.SensitiveTerms
}

func (s *SensitiveContentOptions) GetSensitiveRegexes() []SensitiveExpression {
	if s == nil {
		return nil
	}
	return s.SensitiveRegexes
}
