// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SensitiveContentOptions - Options for defining sensitive content within scanned documents.
type SensitiveContentOptions struct {
	// DEPRECATED - use 'customSensitiveExpressions' instead.
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Use customSensitiveExpressions instead.
	SensitiveInfoTypes []SensitiveInfoType `json:"sensitiveInfoTypes,omitempty"`
	// DEPRECATED - use 'customSensitiveExpressions' instead.
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Use customSensitiveExpressions instead.
	SensitiveTerms []SensitiveExpression `json:"sensitiveTerms,omitempty"`
	// DEPRECATED - use 'customSensitiveExpressions' instead.
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Use customSensitiveExpressions instead.
	SensitiveRegexes []SensitiveExpression `json:"sensitiveRegexes,omitempty"`
	// list of custom sensitive expressions to consider as sensitive content
	CustomSensitiveExpressions []CustomSensitiveExpression `json:"customSensitiveExpressions,omitempty"`
}

func (s *SensitiveContentOptions) GetSensitiveInfoTypes() []SensitiveInfoType {
	if s == nil {
		return nil
	}
	return s.SensitiveInfoTypes
}

func (s *SensitiveContentOptions) GetSensitiveTerms() []SensitiveExpression {
	if s == nil {
		return nil
	}
	return s.SensitiveTerms
}

func (s *SensitiveContentOptions) GetSensitiveRegexes() []SensitiveExpression {
	if s == nil {
		return nil
	}
	return s.SensitiveRegexes
}

func (s *SensitiveContentOptions) GetCustomSensitiveExpressions() []CustomSensitiveExpression {
	if s == nil {
		return nil
	}
	return s.CustomSensitiveExpressions
}
