// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

type Shortcut struct {
	// The opaque id of the user generated content.
	ID *int64 `json:"id,omitempty"`
	// Link text following go/ prefix as entered by the user.
	InputAlias string `json:"inputAlias"`
	// Destination URL for the shortcut.
	DestinationURL *string `json:"destinationUrl,omitempty"`
	// Glean Document ID for the URL, if known.
	DestinationDocumentID *string `json:"destinationDocumentId,omitempty"`
	// A short, plain text blurb to help people understand the intent of the shortcut.
	Description *string `json:"description,omitempty"`
	// Whether this shortcut is unlisted or not. Unlisted shortcuts are visible to author + admins only.
	Unlisted *bool `json:"unlisted,omitempty"`
	// For variable shortcuts, contains the URL template; note, `destinationUrl` contains default URL.
	URLTemplate *string `json:"urlTemplate,omitempty"`
	// A list of user roles added for the Shortcut.
	AddedRoles []UserRoleSpecification `json:"addedRoles,omitempty"`
	// A list of user roles removed for the Shortcut.
	RemovedRoles []UserRoleSpecification `json:"removedRoles,omitempty"`
	Permissions  *ObjectPermissions      `json:"permissions,omitempty"`
	CreatedBy    *Person                 `json:"createdBy,omitempty"`
	// The time the shortcut was created in ISO format (ISO 8601).
	CreateTime *time.Time `json:"createTime,omitempty"`
	UpdatedBy  *Person    `json:"updatedBy,omitempty"`
	// The time the shortcut was updated in ISO format (ISO 8601).
	UpdateTime          *time.Time `json:"updateTime,omitempty"`
	DestinationDocument *Document  `json:"destinationDocument,omitempty"`
	// The URL from which the user is then redirected to the destination URL. Full replacement for https://go/<inputAlias>.
	IntermediateURL *string `json:"intermediateUrl,omitempty"`
	// The part of the shortcut preceding the input alias when used for showing shortcuts to users. Should end with "/". e.g. "go/" for native shortcuts.
	ViewPrefix *string `json:"viewPrefix,omitempty"`
	// Indicates whether a shortcut is native or external.
	IsExternal *bool `json:"isExternal,omitempty"`
	// The URL using which the user can access the edit page of the shortcut.
	EditURL *string `json:"editUrl,omitempty"`
	// canonical link text following go/ prefix where hyphen/underscore is removed.
	Alias *string `json:"alias,omitempty"`
	// Title for the Go Link
	Title *string `json:"title,omitempty"`
	// A list of user roles for the Go Link.
	Roles []UserRoleSpecification `json:"roles,omitempty"`
}

func (s Shortcut) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Shortcut) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Shortcut) GetID() *int64 {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Shortcut) GetInputAlias() string {
	if s == nil {
		return ""
	}
	return s.InputAlias
}

func (s *Shortcut) GetDestinationURL() *string {
	if s == nil {
		return nil
	}
	return s.DestinationURL
}

func (s *Shortcut) GetDestinationDocumentID() *string {
	if s == nil {
		return nil
	}
	return s.DestinationDocumentID
}

func (s *Shortcut) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Shortcut) GetUnlisted() *bool {
	if s == nil {
		return nil
	}
	return s.Unlisted
}

func (s *Shortcut) GetURLTemplate() *string {
	if s == nil {
		return nil
	}
	return s.URLTemplate
}

func (s *Shortcut) GetAddedRoles() []UserRoleSpecification {
	if s == nil {
		return nil
	}
	return s.AddedRoles
}

func (s *Shortcut) GetRemovedRoles() []UserRoleSpecification {
	if s == nil {
		return nil
	}
	return s.RemovedRoles
}

func (s *Shortcut) GetPermissions() *ObjectPermissions {
	if s == nil {
		return nil
	}
	return s.Permissions
}

func (s *Shortcut) GetCreatedBy() *Person {
	if s == nil {
		return nil
	}
	return s.CreatedBy
}

func (s *Shortcut) GetCreateTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreateTime
}

func (s *Shortcut) GetUpdatedBy() *Person {
	if s == nil {
		return nil
	}
	return s.UpdatedBy
}

func (s *Shortcut) GetUpdateTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdateTime
}

func (s *Shortcut) GetDestinationDocument() *Document {
	if s == nil {
		return nil
	}
	return s.DestinationDocument
}

func (s *Shortcut) GetIntermediateURL() *string {
	if s == nil {
		return nil
	}
	return s.IntermediateURL
}

func (s *Shortcut) GetViewPrefix() *string {
	if s == nil {
		return nil
	}
	return s.ViewPrefix
}

func (s *Shortcut) GetIsExternal() *bool {
	if s == nil {
		return nil
	}
	return s.IsExternal
}

func (s *Shortcut) GetEditURL() *string {
	if s == nil {
		return nil
	}
	return s.EditURL
}

func (s *Shortcut) GetAlias() *string {
	if s == nil {
		return nil
	}
	return s.Alias
}

func (s *Shortcut) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *Shortcut) GetRoles() []UserRoleSpecification {
	if s == nil {
		return nil
	}
	return s.Roles
}
