// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ShortcutInsightsResponse struct {
	// Unix timestamp of the last activity processed to make the response (in seconds since epoch UTC).
	LastLogTimestamp *int64 `json:"lastLogTimestamp,omitempty"`
	// Insights for shortcuts.
	ShortcutInsights []ShortcutInsight `json:"shortcutInsights,omitempty"`
	// list of departments applicable for shortcuts tab.
	Departments []string `json:"departments,omitempty"`
	// Min threshold in number of visitors while populating results, otherwise 0.
	MinVisitorThreshold *int64 `json:"minVisitorThreshold,omitempty"`
}

func (s *ShortcutInsightsResponse) GetLastLogTimestamp() *int64 {
	if s == nil {
		return nil
	}
	return s.LastLogTimestamp
}

func (s *ShortcutInsightsResponse) GetShortcutInsights() []ShortcutInsight {
	if s == nil {
		return nil
	}
	return s.ShortcutInsights
}

func (s *ShortcutInsightsResponse) GetDepartments() []string {
	if s == nil {
		return nil
	}
	return s.Departments
}

func (s *ShortcutInsightsResponse) GetMinVisitorThreshold() *int64 {
	if s == nil {
		return nil
	}
	return s.MinVisitorThreshold
}
