// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ResponseMetadata - Metadata about the response (e.g., latency, token count).
type ResponseMetadata struct {
	// Time taken to generate the response in milliseconds.
	LatencyMs *int64 `json:"latencyMs,omitempty"`
	// Number of tokens in the response.
	TokenCount *int64 `json:"tokenCount,omitempty"`
	// The specific model version used.
	ModelUsed *string `json:"modelUsed,omitempty"`
}

func (r *ResponseMetadata) GetLatencyMs() *int64 {
	if r == nil {
		return nil
	}
	return r.LatencyMs
}

func (r *ResponseMetadata) GetTokenCount() *int64 {
	if r == nil {
		return nil
	}
	return r.TokenCount
}

func (r *ResponseMetadata) GetModelUsed() *string {
	if r == nil {
		return nil
	}
	return r.ModelUsed
}

type SideBySideImplementation struct {
	// Unique identifier for this implementation variant.
	ImplementationID *string `json:"implementationId,omitempty"`
	// Human-readable name for this implementation (e.g., "Variant A", "GPT-4", "Claude").
	ImplementationName *string `json:"implementationName,omitempty"`
	// The search/chat parameters used for this implementation.
	SearchParams map[string]string `json:"searchParams,omitempty"`
	// The full response generated by this implementation.
	Response *string `json:"response,omitempty"`
	// Metadata about the response (e.g., latency, token count).
	ResponseMetadata *ResponseMetadata `json:"responseMetadata,omitempty"`
}

func (s *SideBySideImplementation) GetImplementationID() *string {
	if s == nil {
		return nil
	}
	return s.ImplementationID
}

func (s *SideBySideImplementation) GetImplementationName() *string {
	if s == nil {
		return nil
	}
	return s.ImplementationName
}

func (s *SideBySideImplementation) GetSearchParams() map[string]string {
	if s == nil {
		return nil
	}
	return s.SearchParams
}

func (s *SideBySideImplementation) GetResponse() *string {
	if s == nil {
		return nil
	}
	return s.Response
}

func (s *SideBySideImplementation) GetResponseMetadata() *ResponseMetadata {
	if s == nil {
		return nil
	}
	return s.ResponseMetadata
}
