// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SocialNetworkDefinition - Employee's social network profile
type SocialNetworkDefinition struct {
	// Possible values are "twitter", "linkedin".
	Name *string `json:"name,omitempty"`
	// Human-readable profile name.
	ProfileName *string `json:"profileName,omitempty"`
	// Link to profile.
	ProfileURL *string `json:"profileUrl,omitempty"`
}

func (s *SocialNetworkDefinition) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SocialNetworkDefinition) GetProfileName() *string {
	if s == nil {
		return nil
	}
	return s.ProfileName
}

func (s *SocialNetworkDefinition) GetProfileURL() *string {
	if s == nil {
		return nil
	}
	return s.ProfileURL
}
