// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// Prominence - The level of visual distinction that should be given to a result.
type Prominence string

const (
	// ProminenceHero A high-confidence result that should feature prominently on the page.
	ProminenceHero Prominence = "HERO"
	// ProminencePromoted May not be the best result but should be given additional visual distinction.
	ProminencePromoted Prominence = "PROMOTED"
	// ProminenceStandard Should not be distinct from any other results.
	ProminenceStandard Prominence = "STANDARD"
)

func (e Prominence) ToPointer() *Prominence {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Prominence) IsExact() bool {
	if e != nil {
		switch *e {
		case "HERO", "PROMOTED", "STANDARD":
			return true
		}
	}
	return false
}

// StructuredResultSource - Source context for this result. Possible values depend on the result type.
type StructuredResultSource string

const (
	StructuredResultSourceExpertDetection StructuredResultSource = "EXPERT_DETECTION"
	StructuredResultSourceEntityNlq       StructuredResultSource = "ENTITY_NLQ"
	StructuredResultSourceCalendarEvent   StructuredResultSource = "CALENDAR_EVENT"
	StructuredResultSourceAgent           StructuredResultSource = "AGENT"
)

func (e StructuredResultSource) ToPointer() *StructuredResultSource {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StructuredResultSource) IsExact() bool {
	if e != nil {
		switch *e {
		case "EXPERT_DETECTION", "ENTITY_NLQ", "CALENDAR_EVENT", "AGENT":
			return true
		}
	}
	return false
}

// StructuredResult - A single object that can support any object in the work graph. Only a single object will be populated.
type StructuredResult struct {
	Document         *Document            `json:"document,omitempty"`
	Person           *Person              `json:"person,omitempty"`
	Customer         *Customer            `json:"customer,omitempty"`
	Team             *Team                `json:"team,omitempty"`
	CustomEntity     *CustomEntity        `json:"customEntity,omitempty"`
	Answer           *Answer              `json:"answer,omitempty"`
	GeneratedQna     *GeneratedQna        `json:"generatedQna,omitempty"`
	ExtractedQnA     *ExtractedQnA        `json:"extractedQnA,omitempty"`
	Meeting          *Meeting             `json:"meeting,omitempty"`
	App              *AppResult           `json:"app,omitempty"`
	Collection       *Collection          `json:"collection,omitempty"`
	Code             *Code                `json:"code,omitempty"`
	Shortcut         *Shortcut            `json:"shortcut,omitempty"`
	QuerySuggestions *QuerySuggestionList `json:"querySuggestions,omitempty"`
	// Metadata of a Chat a user had with Glean Assistant. This contains no actual conversational content.
	Chat *ChatMetadata `json:"chat,omitempty"`
	// A list of documents related to this structured result.
	RelatedDocuments []RelatedDocuments `json:"relatedDocuments,omitempty"`
	RelatedQuestion  *RelatedQuestion   `json:"relatedQuestion,omitempty"`
	// A disambiguation between multiple entities with the same name
	Disambiguation *Disambiguation `json:"disambiguation,omitempty"`
	// Any snippets associated to the populated object.
	Snippets []SearchResultSnippet `json:"snippets,omitempty"`
	// An opaque token that represents this particular result in this particular query. To be used for /feedback reporting.
	TrackingToken *string `json:"trackingToken,omitempty"`
	// The level of visual distinction that should be given to a result.
	Prominence *Prominence `json:"prominence,omitempty"`
	// Source context for this result. Possible values depend on the result type.
	Source *StructuredResultSource `json:"source,omitempty"`
}

func (s StructuredResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StructuredResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StructuredResult) GetDocument() *Document {
	if s == nil {
		return nil
	}
	return s.Document
}

func (s *StructuredResult) GetPerson() *Person {
	if s == nil {
		return nil
	}
	return s.Person
}

func (s *StructuredResult) GetCustomer() *Customer {
	if s == nil {
		return nil
	}
	return s.Customer
}

func (s *StructuredResult) GetTeam() *Team {
	if s == nil {
		return nil
	}
	return s.Team
}

func (s *StructuredResult) GetCustomEntity() *CustomEntity {
	if s == nil {
		return nil
	}
	return s.CustomEntity
}

func (s *StructuredResult) GetAnswer() *Answer {
	if s == nil {
		return nil
	}
	return s.Answer
}

func (s *StructuredResult) GetGeneratedQna() *GeneratedQna {
	if s == nil {
		return nil
	}
	return s.GeneratedQna
}

func (s *StructuredResult) GetExtractedQnA() *ExtractedQnA {
	if s == nil {
		return nil
	}
	return s.ExtractedQnA
}

func (s *StructuredResult) GetMeeting() *Meeting {
	if s == nil {
		return nil
	}
	return s.Meeting
}

func (s *StructuredResult) GetApp() *AppResult {
	if s == nil {
		return nil
	}
	return s.App
}

func (s *StructuredResult) GetCollection() *Collection {
	if s == nil {
		return nil
	}
	return s.Collection
}

func (s *StructuredResult) GetCode() *Code {
	if s == nil {
		return nil
	}
	return s.Code
}

func (s *StructuredResult) GetShortcut() *Shortcut {
	if s == nil {
		return nil
	}
	return s.Shortcut
}

func (s *StructuredResult) GetQuerySuggestions() *QuerySuggestionList {
	if s == nil {
		return nil
	}
	return s.QuerySuggestions
}

func (s *StructuredResult) GetChat() *ChatMetadata {
	if s == nil {
		return nil
	}
	return s.Chat
}

func (s *StructuredResult) GetRelatedDocuments() []RelatedDocuments {
	if s == nil {
		return nil
	}
	return s.RelatedDocuments
}

func (s *StructuredResult) GetRelatedQuestion() *RelatedQuestion {
	if s == nil {
		return nil
	}
	return s.RelatedQuestion
}

func (s *StructuredResult) GetDisambiguation() *Disambiguation {
	if s == nil {
		return nil
	}
	return s.Disambiguation
}

func (s *StructuredResult) GetSnippets() []SearchResultSnippet {
	if s == nil {
		return nil
	}
	return s.Snippets
}

func (s *StructuredResult) GetTrackingToken() *string {
	if s == nil {
		return nil
	}
	return s.TrackingToken
}

func (s *StructuredResult) GetProminence() *Prominence {
	if s == nil {
		return nil
	}
	return s.Prominence
}

func (s *StructuredResult) GetSource() *StructuredResultSource {
	if s == nil {
		return nil
	}
	return s.Source
}
