// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Error struct {
	Message *string `json:"message,omitempty"`
}

func (e *Error) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

type SummarizeResponse struct {
	Error   *Error   `json:"error,omitempty"`
	Summary *Summary `json:"summary,omitempty"`
	// An opaque token that represents this summary in this particular query. To be used for /feedback reporting.
	TrackingToken *string `json:"trackingToken,omitempty"`
}

func (s *SummarizeResponse) GetError() *Error {
	if s == nil {
		return nil
	}
	return s.Error
}

func (s *SummarizeResponse) GetSummary() *Summary {
	if s == nil {
		return nil
	}
	return s.Summary
}

func (s *SummarizeResponse) GetTrackingToken() *string {
	if s == nil {
		return nil
	}
	return s.TrackingToken
}
