// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TeamInfoDefinition - Information about an employee's team
type TeamInfoDefinition struct {
	// The unique ID of the team
	ID string `json:"id"`
	// Human-readable team name
	Name string `json:"name"`
	// The description of this team
	Description *string `json:"description,omitempty"`
	// Typically the highest level organizational unit; generally applies to bigger companies with multiple distinct businesses.
	BusinessUnit *string `json:"businessUnit,omitempty"`
	// An organizational unit where everyone has a similar task, e.g. `Engineering`.
	Department *string `json:"department,omitempty"`
	// A link to the team's photo
	PhotoURL *string `json:"photoUrl,omitempty"`
	// A link to an external team page. If set, team results will link to it.
	//
	ExternalLink *string `json:"externalLink,omitempty"`
	// The emails of the team
	Emails []TeamEmail `json:"emails,omitempty"`
	// The datasource profiles of the team, e.g. `Slack`,`Github`.
	DatasourceProfiles []DatasourceProfile `json:"datasourceProfiles,omitempty"`
	// The members of the team
	Members []TeamMember `json:"members"`
	// List of additional fields with more information about the team.
	AdditionalFields []AdditionalFieldDefinition `json:"additionalFields,omitempty"`
}

func (t *TeamInfoDefinition) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TeamInfoDefinition) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TeamInfoDefinition) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TeamInfoDefinition) GetBusinessUnit() *string {
	if t == nil {
		return nil
	}
	return t.BusinessUnit
}

func (t *TeamInfoDefinition) GetDepartment() *string {
	if t == nil {
		return nil
	}
	return t.Department
}

func (t *TeamInfoDefinition) GetPhotoURL() *string {
	if t == nil {
		return nil
	}
	return t.PhotoURL
}

func (t *TeamInfoDefinition) GetExternalLink() *string {
	if t == nil {
		return nil
	}
	return t.ExternalLink
}

func (t *TeamInfoDefinition) GetEmails() []TeamEmail {
	if t == nil {
		return nil
	}
	return t.Emails
}

func (t *TeamInfoDefinition) GetDatasourceProfiles() []DatasourceProfile {
	if t == nil {
		return nil
	}
	return t.DatasourceProfiles
}

func (t *TeamInfoDefinition) GetMembers() []TeamMember {
	if t == nil {
		return []TeamMember{}
	}
	return t.Members
}

func (t *TeamInfoDefinition) GetAdditionalFields() []AdditionalFieldDefinition {
	if t == nil {
		return nil
	}
	return t.AdditionalFields
}
