// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

// TeamStatus - whether this team is fully processed or there are still unprocessed operations that'll affect it
type TeamStatus string

const (
	TeamStatusProcessed         TeamStatus = "PROCESSED"
	TeamStatusQueuedForCreation TeamStatus = "QUEUED_FOR_CREATION"
	TeamStatusQueuedForDeletion TeamStatus = "QUEUED_FOR_DELETION"
)

func (e TeamStatus) ToPointer() *TeamStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TeamStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "PROCESSED", "QUEUED_FOR_CREATION", "QUEUED_FOR_DELETION":
			return true
		}
	}
	return false
}

type Team struct {
	// A list of objects related to a source object.
	RelatedObjects map[string]RelatedObjectEdge `json:"relatedObjects,omitempty"`
	Permissions    *ObjectPermissions           `json:"permissions,omitempty"`
	// Unique identifier
	ID string `json:"id"`
	// Team name
	Name string `json:"name"`
	// A description of the team
	Description *string `json:"description,omitempty"`
	// Typically the highest level organizational unit; generally applies to bigger companies with multiple distinct businesses.
	BusinessUnit *string `json:"businessUnit,omitempty"`
	// An organizational unit where everyone has a similar task, e.g. `Engineering`.
	Department *string `json:"department,omitempty"`
	// A link to the team's photo.
	PhotoURL *string `json:"photoUrl,omitempty"`
	// A link to the team's banner photo.
	BannerURL *string `json:"bannerUrl,omitempty"`
	// Link to a team page on the internet or your company's intranet
	ExternalLink *string `json:"externalLink,omitempty"`
	// The members on this team
	Members []PersonToTeamRelationship `json:"members,omitempty"`
	// Number of members on this team (recursive; includes all individuals that belong to this team, and all individuals that belong to a subteam within this team)
	MemberCount *int64 `json:"memberCount,omitempty"`
	// The emails for this team
	Emails []TeamEmail `json:"emails,omitempty"`
	// Customizable fields for additional team information.
	CustomFields []CustomFieldData `json:"customFields,omitempty"`
	// The datasource profiles of the team
	DatasourceProfiles []DatasourceProfile `json:"datasourceProfiles,omitempty"`
	// the data source of the team, e.g. GDRIVE
	Datasource *string `json:"datasource,omitempty"`
	// For teams created from docs, the doc title. Otherwise empty.
	CreatedFrom *string `json:"createdFrom,omitempty"`
	// when this team was last updated.
	LastUpdatedAt *time.Time `json:"lastUpdatedAt,omitempty"`
	// whether this team is fully processed or there are still unprocessed operations that'll affect it
	Status *TeamStatus `default:"PROCESSED" json:"status"`
	// can this team be deleted. Some manually ingested teams like GCS_CSV or PUSH_API cannot
	CanBeDeleted *bool `default:"true" json:"canBeDeleted"`
	// The logging id of the team used in scrubbed logs, client analytics, and metrics.
	LoggingID *string `json:"loggingId,omitempty"`
}

func (t Team) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Team) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Team) GetRelatedObjects() map[string]RelatedObjectEdge {
	if t == nil {
		return nil
	}
	return t.RelatedObjects
}

func (t *Team) GetPermissions() *ObjectPermissions {
	if t == nil {
		return nil
	}
	return t.Permissions
}

func (t *Team) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Team) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Team) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Team) GetBusinessUnit() *string {
	if t == nil {
		return nil
	}
	return t.BusinessUnit
}

func (t *Team) GetDepartment() *string {
	if t == nil {
		return nil
	}
	return t.Department
}

func (t *Team) GetPhotoURL() *string {
	if t == nil {
		return nil
	}
	return t.PhotoURL
}

func (t *Team) GetBannerURL() *string {
	if t == nil {
		return nil
	}
	return t.BannerURL
}

func (t *Team) GetExternalLink() *string {
	if t == nil {
		return nil
	}
	return t.ExternalLink
}

func (t *Team) GetMembers() []PersonToTeamRelationship {
	if t == nil {
		return nil
	}
	return t.Members
}

func (t *Team) GetMemberCount() *int64 {
	if t == nil {
		return nil
	}
	return t.MemberCount
}

func (t *Team) GetEmails() []TeamEmail {
	if t == nil {
		return nil
	}
	return t.Emails
}

func (t *Team) GetCustomFields() []CustomFieldData {
	if t == nil {
		return nil
	}
	return t.CustomFields
}

func (t *Team) GetDatasourceProfiles() []DatasourceProfile {
	if t == nil {
		return nil
	}
	return t.DatasourceProfiles
}

func (t *Team) GetDatasource() *string {
	if t == nil {
		return nil
	}
	return t.Datasource
}

func (t *Team) GetCreatedFrom() *string {
	if t == nil {
		return nil
	}
	return t.CreatedFrom
}

func (t *Team) GetLastUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.LastUpdatedAt
}

func (t *Team) GetStatus() *TeamStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *Team) GetCanBeDeleted() *bool {
	if t == nil {
		return nil
	}
	return t.CanBeDeleted
}

func (t *Team) GetLoggingID() *string {
	if t == nil {
		return nil
	}
	return t.LoggingID
}
