// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type TextRangeType string

const (
	TextRangeTypeBold      TextRangeType = "BOLD"
	TextRangeTypeCitation  TextRangeType = "CITATION"
	TextRangeTypeHighlight TextRangeType = "HIGHLIGHT"
	TextRangeTypeLink      TextRangeType = "LINK"
)

func (e TextRangeType) ToPointer() *TextRangeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TextRangeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "BOLD", "CITATION", "HIGHLIGHT", "LINK":
			return true
		}
	}
	return false
}

// TextRange - A subsection of a given string to which some special formatting should be applied.
type TextRange struct {
	// The inclusive start index of the range.
	StartIndex int64 `json:"startIndex"`
	// The exclusive end index of the range.
	EndIndex *int64         `json:"endIndex,omitempty"`
	Type     *TextRangeType `json:"type,omitempty"`
	// The URL associated with the range, if applicable. For example, the linked URL for a LINK range.
	URL      *string   `json:"url,omitempty"`
	Document *Document `json:"document,omitempty"`
}

func (t TextRange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextRange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TextRange) GetStartIndex() int64 {
	if t == nil {
		return 0
	}
	return t.StartIndex
}

func (t *TextRange) GetEndIndex() *int64 {
	if t == nil {
		return nil
	}
	return t.EndIndex
}

func (t *TextRange) GetType() *TextRangeType {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TextRange) GetURL() *string {
	if t == nil {
		return nil
	}
	return t.URL
}

func (t *TextRange) GetDocument() *Document {
	if t == nil {
		return nil
	}
	return t.Document
}
