// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type Thumbnail struct {
	// Photo id if the thumbnail is from splash.
	PhotoID *string `json:"photoId,omitempty"`
	// Thumbnail URL. This can be user provided image and/or from downloaded images hosted by Glean.
	URL *string `json:"url,omitempty"`
}

func (t Thumbnail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Thumbnail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Thumbnail) GetPhotoID() *string {
	if t == nil {
		return nil
	}
	return t.PhotoID
}

func (t *Thumbnail) GetURL() *string {
	if t == nil {
		return nil
	}
	return t.URL
}
