// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TimeRangeFilterTimePeriodType - The type of time period for which to filter findings.
type TimeRangeFilterTimePeriodType string

const (
	TimeRangeFilterTimePeriodTypePastDay   TimeRangeFilterTimePeriodType = "PAST_DAY"
	TimeRangeFilterTimePeriodTypePastWeek  TimeRangeFilterTimePeriodType = "PAST_WEEK"
	TimeRangeFilterTimePeriodTypePastMonth TimeRangeFilterTimePeriodType = "PAST_MONTH"
	TimeRangeFilterTimePeriodTypePastYear  TimeRangeFilterTimePeriodType = "PAST_YEAR"
	TimeRangeFilterTimePeriodTypeCustom    TimeRangeFilterTimePeriodType = "CUSTOM"
)

func (e TimeRangeFilterTimePeriodType) ToPointer() *TimeRangeFilterTimePeriodType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TimeRangeFilterTimePeriodType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PAST_DAY", "PAST_WEEK", "PAST_MONTH", "PAST_YEAR", "CUSTOM":
			return true
		}
	}
	return false
}

type TimeRangeFilter struct {
	// The type of time period for which to filter findings.
	TimePeriodType  *TimeRangeFilterTimePeriodType `json:"timePeriodType,omitempty"`
	CustomTimeRange *TimeRange                     `json:"customTimeRange,omitempty"`
}

func (t *TimeRangeFilter) GetTimePeriodType() *TimeRangeFilterTimePeriodType {
	if t == nil {
		return nil
	}
	return t.TimePeriodType
}

func (t *TimeRangeFilter) GetCustomTimeRange() *TimeRange {
	if t == nil {
		return nil
	}
	return t.CustomTimeRange
}
