// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ToolsCallResponse struct {
	// The raw response from the tool
	RawResponse map[string]any `json:"rawResponse,omitempty"`
	// The error message if applicable
	Error *string `json:"error,omitempty"`
}

func (t *ToolsCallResponse) GetRawResponse() map[string]any {
	if t == nil {
		return nil
	}
	return t.RawResponse
}

func (t *ToolsCallResponse) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}
