// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ToolsListResponse struct {
	Tools []Tool `json:"tools,omitempty"`
}

func (o *ToolsListResponse) GetTools() []Tool {
	if o == nil {
		return nil
	}
	return o.Tools
}
