// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDlpConfigRequest struct {
	// Detailed configuration of what documents and sensitive content will be scanned.
	Config *DlpConfig `json:"config,omitempty"`
	// Only "ONCE" is supported for reports.
	Frequency *string `json:"frequency,omitempty"`
}

func (u *UpdateDlpConfigRequest) GetConfig() *DlpConfig {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpdateDlpConfigRequest) GetFrequency() *string {
	if u == nil {
		return nil
	}
	return u.Frequency
}
