// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDocumentVisibilityOverridesResponse struct {
	// The documents and whether their visibility was successfully updated.
	Results []DocumentVisibilityUpdateResult `json:"results,omitempty"`
}

func (u *UpdateDocumentVisibilityOverridesResponse) GetResults() []DocumentVisibilityUpdateResult {
	if u == nil {
		return nil
	}
	return u.Results
}
