// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

// UpdateAnnouncementRequestChannel - This determines whether this is a Social Feed post or a regular announcement.
type UpdateAnnouncementRequestChannel string

const (
	UpdateAnnouncementRequestChannelMain       UpdateAnnouncementRequestChannel = "MAIN"
	UpdateAnnouncementRequestChannelSocialFeed UpdateAnnouncementRequestChannel = "SOCIAL_FEED"
)

func (e UpdateAnnouncementRequestChannel) ToPointer() *UpdateAnnouncementRequestChannel {
	return &e
}
func (e *UpdateAnnouncementRequestChannel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MAIN":
		fallthrough
	case "SOCIAL_FEED":
		*e = UpdateAnnouncementRequestChannel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateAnnouncementRequestChannel: %v", v)
	}
}

// UpdateAnnouncementRequestPostType - This determines whether this is an external-link post or a regular announcement post. TEXT - Regular announcement that can contain rich text. LINK - Announcement that is linked to an external site.
type UpdateAnnouncementRequestPostType string

const (
	UpdateAnnouncementRequestPostTypeText UpdateAnnouncementRequestPostType = "TEXT"
	UpdateAnnouncementRequestPostTypeLink UpdateAnnouncementRequestPostType = "LINK"
)

func (e UpdateAnnouncementRequestPostType) ToPointer() *UpdateAnnouncementRequestPostType {
	return &e
}
func (e *UpdateAnnouncementRequestPostType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TEXT":
		fallthrough
	case "LINK":
		*e = UpdateAnnouncementRequestPostType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateAnnouncementRequestPostType: %v", v)
	}
}

type UpdateAnnouncementRequest struct {
	// The date and time at which the announcement becomes active.
	StartTime time.Time `json:"startTime"`
	// The date and time at which the announcement expires.
	EndTime time.Time `json:"endTime"`
	// The headline of the announcement.
	Title string          `json:"title"`
	Body  *StructuredText `json:"body,omitempty"`
	// An emoji used to indicate the nature of the announcement.
	Emoji     *string    `json:"emoji,omitempty"`
	Thumbnail *Thumbnail `json:"thumbnail,omitempty"`
	Banner    *Thumbnail `json:"banner,omitempty"`
	// Filters which restrict who should see the announcement. Values are taken from the corresponding filters in people search.
	AudienceFilters []FacetFilter `json:"audienceFilters,omitempty"`
	// The Glean Document ID of the source document this Announcement was created from (e.g. Slack thread).
	SourceDocumentID *string `json:"sourceDocumentId,omitempty"`
	// Whether or not to hide an author attribution.
	HideAttribution *bool `json:"hideAttribution,omitempty"`
	// This determines whether this is a Social Feed post or a regular announcement.
	Channel *UpdateAnnouncementRequestChannel `json:"channel,omitempty"`
	// This determines whether this is an external-link post or a regular announcement post. TEXT - Regular announcement that can contain rich text. LINK - Announcement that is linked to an external site.
	PostType *UpdateAnnouncementRequestPostType `json:"postType,omitempty"`
	// Used by the Social Feed to pin posts to the front of the feed.
	IsPrioritized *bool `json:"isPrioritized,omitempty"`
	// URL for viewing the announcement. It will be set to document URL for announcements from other datasources e.g. simpplr. Can only be written when channel="SOCIAL_FEED".
	ViewURL *string `json:"viewUrl,omitempty"`
	// The opaque id of the announcement.
	ID int64 `json:"id"`
}

func (u UpdateAnnouncementRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAnnouncementRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"startTime", "endTime", "title", "id"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAnnouncementRequest) GetStartTime() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.StartTime
}

func (u *UpdateAnnouncementRequest) GetEndTime() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.EndTime
}

func (u *UpdateAnnouncementRequest) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

func (u *UpdateAnnouncementRequest) GetBody() *StructuredText {
	if u == nil {
		return nil
	}
	return u.Body
}

func (u *UpdateAnnouncementRequest) GetEmoji() *string {
	if u == nil {
		return nil
	}
	return u.Emoji
}

func (u *UpdateAnnouncementRequest) GetThumbnail() *Thumbnail {
	if u == nil {
		return nil
	}
	return u.Thumbnail
}

func (u *UpdateAnnouncementRequest) GetBanner() *Thumbnail {
	if u == nil {
		return nil
	}
	return u.Banner
}

func (u *UpdateAnnouncementRequest) GetAudienceFilters() []FacetFilter {
	if u == nil {
		return nil
	}
	return u.AudienceFilters
}

func (u *UpdateAnnouncementRequest) GetSourceDocumentID() *string {
	if u == nil {
		return nil
	}
	return u.SourceDocumentID
}

func (u *UpdateAnnouncementRequest) GetHideAttribution() *bool {
	if u == nil {
		return nil
	}
	return u.HideAttribution
}

func (u *UpdateAnnouncementRequest) GetChannel() *UpdateAnnouncementRequestChannel {
	if u == nil {
		return nil
	}
	return u.Channel
}

func (u *UpdateAnnouncementRequest) GetPostType() *UpdateAnnouncementRequestPostType {
	if u == nil {
		return nil
	}
	return u.PostType
}

func (u *UpdateAnnouncementRequest) GetIsPrioritized() *bool {
	if u == nil {
		return nil
	}
	return u.IsPrioritized
}

func (u *UpdateAnnouncementRequest) GetViewURL() *string {
	if u == nil {
		return nil
	}
	return u.ViewURL
}

func (u *UpdateAnnouncementRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}
