// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDlpReportRequest struct {
	// Detailed configuration of what documents and sensitive content will be scanned.
	Config *DlpConfig `json:"config,omitempty"`
	// Interval between scans. DAILY is deprecated.
	Frequency *DlpFrequency `json:"frequency,omitempty"`
	// The status of the policy/report. Only ACTIVE status will be picked for scans.
	Status *DlpReportStatus `json:"status,omitempty"`
	// The new autoHideDoc boolean the policy will be updated to if provided.
	AutoHideDocs *bool `json:"autoHideDocs,omitempty"`
	// The new name of the policy if provided.
	ReportName *string `json:"reportName,omitempty"`
}

func (u *UpdateDlpReportRequest) GetConfig() *DlpConfig {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpdateDlpReportRequest) GetFrequency() *DlpFrequency {
	if u == nil {
		return nil
	}
	return u.Frequency
}

func (u *UpdateDlpReportRequest) GetStatus() *DlpReportStatus {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateDlpReportRequest) GetAutoHideDocs() *bool {
	if u == nil {
		return nil
	}
	return u.AutoHideDocs
}

func (u *UpdateDlpReportRequest) GetReportName() *string {
	if u == nil {
		return nil
	}
	return u.ReportName
}
