// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateShortcutRequest struct {
	// The opaque id of the user generated content.
	ID int64 `json:"id"`
	// Link text following go/ prefix as entered by the user.
	InputAlias *string `json:"inputAlias,omitempty"`
	// Destination URL for the shortcut.
	DestinationURL *string `json:"destinationUrl,omitempty"`
	// Glean Document ID for the URL, if known.
	DestinationDocumentID *string `json:"destinationDocumentId,omitempty"`
	// A short, plain text blurb to help people understand the intent of the shortcut.
	Description *string `json:"description,omitempty"`
	// Whether this shortcut is unlisted or not. Unlisted shortcuts are visible to author + admins only.
	Unlisted *bool `json:"unlisted,omitempty"`
	// For variable shortcuts, contains the URL template; note, `destinationUrl` contains default URL.
	URLTemplate *string `json:"urlTemplate,omitempty"`
	// A list of user roles added for the Shortcut.
	AddedRoles []UserRoleSpecification `json:"addedRoles,omitempty"`
	// A list of user roles removed for the Shortcut.
	RemovedRoles []UserRoleSpecification `json:"removedRoles,omitempty"`
}

func (u *UpdateShortcutRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateShortcutRequest) GetInputAlias() *string {
	if u == nil {
		return nil
	}
	return u.InputAlias
}

func (u *UpdateShortcutRequest) GetDestinationURL() *string {
	if u == nil {
		return nil
	}
	return u.DestinationURL
}

func (u *UpdateShortcutRequest) GetDestinationDocumentID() *string {
	if u == nil {
		return nil
	}
	return u.DestinationDocumentID
}

func (u *UpdateShortcutRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateShortcutRequest) GetUnlisted() *bool {
	if u == nil {
		return nil
	}
	return u.Unlisted
}

func (u *UpdateShortcutRequest) GetURLTemplate() *string {
	if u == nil {
		return nil
	}
	return u.URLTemplate
}

func (u *UpdateShortcutRequest) GetAddedRoles() []UserRoleSpecification {
	if u == nil {
		return nil
	}
	return u.AddedRoles
}

func (u *UpdateShortcutRequest) GetRemovedRoles() []UserRoleSpecification {
	if u == nil {
		return nil
	}
	return u.RemovedRoles
}
