// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UploadStatusEnum - Upload status, enum of NOT_UPLOADED, UPLOADED, STATUS_UNKNOWN
type UploadStatusEnum string

const (
	UploadStatusEnumUploaded      UploadStatusEnum = "UPLOADED"
	UploadStatusEnumNotUploaded   UploadStatusEnum = "NOT_UPLOADED"
	UploadStatusEnumStatusUnknown UploadStatusEnum = "STATUS_UNKNOWN"
)

func (e UploadStatusEnum) ToPointer() *UploadStatusEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UploadStatusEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "UPLOADED", "NOT_UPLOADED", "STATUS_UNKNOWN":
			return true
		}
	}
	return false
}
