// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserViewInfo struct {
	// Unique Glean Document ID of the associated document.
	DocID *string `json:"docId,omitempty"`
	// Title of associated document.
	DocTitle *string `json:"docTitle,omitempty"`
	// URL of associated document.
	DocURL *string `json:"docUrl,omitempty"`
}

func (u *UserViewInfo) GetDocID() *string {
	if u == nil {
		return nil
	}
	return u.DocID
}

func (u *UserViewInfo) GetDocTitle() *string {
	if u == nil {
		return nil
	}
	return u.DocTitle
}

func (u *UserViewInfo) GetDocURL() *string {
	if u == nil {
		return nil
	}
	return u.DocURL
}
