// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type VerificationMetadata struct {
	LastVerifier *Person `json:"lastVerifier,omitempty"`
	// The unix timestamp of the verification (in seconds since epoch UTC).
	LastVerificationTs *int64 `json:"lastVerificationTs,omitempty"`
	// The unix timestamp of the verification expiration if applicable (in seconds since epoch UTC).
	ExpirationTs *int64    `json:"expirationTs,omitempty"`
	Document     *Document `json:"document,omitempty"`
	// Info about all outstanding verification reminders for the document if exists.
	Reminders    []Reminder `json:"reminders,omitempty"`
	LastReminder *Reminder  `json:"lastReminder,omitempty"`
	// Number of visitors to the document during included time periods.
	VisitorCount []CountInfo `json:"visitorCount,omitempty"`
	// List of potential verifiers for the document e.g. old verifiers and/or users with view/edit permissions.
	CandidateVerifiers []Person `json:"candidateVerifiers,omitempty"`
}

func (v VerificationMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VerificationMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VerificationMetadata) GetLastVerifier() *Person {
	if v == nil {
		return nil
	}
	return v.LastVerifier
}

func (v *VerificationMetadata) GetLastVerificationTs() *int64 {
	if v == nil {
		return nil
	}
	return v.LastVerificationTs
}

func (v *VerificationMetadata) GetExpirationTs() *int64 {
	if v == nil {
		return nil
	}
	return v.ExpirationTs
}

func (v *VerificationMetadata) GetDocument() *Document {
	if v == nil {
		return nil
	}
	return v.Document
}

func (v *VerificationMetadata) GetReminders() []Reminder {
	if v == nil {
		return nil
	}
	return v.Reminders
}

func (v *VerificationMetadata) GetLastReminder() *Reminder {
	if v == nil {
		return nil
	}
	return v.LastReminder
}

func (v *VerificationMetadata) GetVisitorCount() []CountInfo {
	if v == nil {
		return nil
	}
	return v.VisitorCount
}

func (v *VerificationMetadata) GetCandidateVerifiers() []Person {
	if v == nil {
		return nil
	}
	return v.CandidateVerifiers
}
