// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowResult struct {
	Workflow Workflow `json:"workflow"`
}

func (w *WorkflowResult) GetWorkflow() Workflow {
	if w == nil {
		return Workflow{}
	}
	return w.Workflow
}
