// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type AuthToken struct {
	AccessToken string  `json:"accessToken"`
	Datasource  string  `json:"datasource"`
	Scope       *string `json:"scope,omitempty"`
	TokenType   *string `json:"tokenType,omitempty"`
	// Used by Google to indicate the index of the logged in user. Useful for generating hyperlinks that support multilogin.
	AuthUser *string `json:"authUser,omitempty"`
	// Unix timestamp when this token expires (in seconds since epoch UTC).
	Expiration *int64 `json:"expiration,omitempty"`
}

func (a AuthToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"accessToken", "datasource"}); err != nil {
		return err
	}
	return nil
}

func (o *AuthToken) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *AuthToken) GetDatasource() string {
	if o == nil {
		return ""
	}
	return o.Datasource
}

func (o *AuthToken) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *AuthToken) GetTokenType() *string {
	if o == nil {
		return nil
	}
	return o.TokenType
}

func (o *AuthToken) GetAuthUser() *string {
	if o == nil {
		return nil
	}
	return o.AuthUser
}

func (o *AuthToken) GetExpiration() *int64 {
	if o == nil {
		return nil
	}
	return o.Expiration
}
