// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type CollectionPinTarget struct {
	// Categories a Collection can be pinned to.
	Category CollectionPinnableCategories `json:"category"`
	// Optional. If category supports values, then the additional value for the category e.g. department name for DEPARTMENT_RESOURCE, team name/id for TEAM_RESOURCE and so on.
	Value *string `json:"value,omitempty"`
	// What targets can a Collection be pinned to.
	Target *CollectionPinnableTargets `json:"target,omitempty"`
}

func (c CollectionPinTarget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectionPinTarget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"category"}); err != nil {
		return err
	}
	return nil
}

func (o *CollectionPinTarget) GetCategory() CollectionPinnableCategories {
	if o == nil {
		return CollectionPinnableCategories("")
	}
	return o.Category
}

func (o *CollectionPinTarget) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *CollectionPinTarget) GetTarget() *CollectionPinnableTargets {
	if o == nil {
		return nil
	}
	return o.Target
}
