// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDlpReportResponse struct {
	// Full policy information that will be used for scans.
	Report *DlpReport `json:"report,omitempty"`
}

func (o *CreateDlpReportResponse) GetReport() *DlpReport {
	if o == nil {
		return nil
	}
	return o.Report
}
