// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type CustomFieldValueHyperlink struct {
	// Anchor text for hyperlink.
	URLAnchor *string `json:"urlAnchor,omitempty"`
	// Link for this URL.
	URLLink *string `json:"urlLink,omitempty"`
}

func (c CustomFieldValueHyperlink) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomFieldValueHyperlink) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *CustomFieldValueHyperlink) GetURLAnchor() *string {
	if o == nil {
		return nil
	}
	return o.URLAnchor
}

func (o *CustomFieldValueHyperlink) GetURLLink() *string {
	if o == nil {
		return nil
	}
	return o.URLLink
}
