// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ExternalSharingOptions - Controls how "shared" a document must be to get picked for scans.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type ExternalSharingOptions struct {
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Enabled *bool `json:"enabled,omitempty"`
	// The minimum number of users the document is shared with.
	Threshold *int64 `json:"threshold,omitempty"`
	// Documents will be filtered based on how many people have access to it.
	ThresholdEnabled *bool `json:"thresholdEnabled,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AnyoneWithLinkEnabled *bool `json:"anyoneWithLinkEnabled,omitempty"`
	// Only users within the organization can access the document.
	AnyoneInternalEnabled *bool `json:"anyoneInternalEnabled,omitempty"`
	// Anyone on the internet can access the document.
	AnonymousAccessEnabled *bool `json:"anonymousAccessEnabled,omitempty"`
	// Enable user access check
	UserAccessEnabled *bool `json:"userAccessEnabled,omitempty"`
	// Any one of the specified users can access the document.
	UserIds             []string `json:"userIds,omitempty"`
	DomainAccessEnabled *bool    `json:"domainAccessEnabled,omitempty"`
}

func (o *ExternalSharingOptions) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ExternalSharingOptions) GetThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.Threshold
}

func (o *ExternalSharingOptions) GetThresholdEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.ThresholdEnabled
}

func (o *ExternalSharingOptions) GetAnyoneWithLinkEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AnyoneWithLinkEnabled
}

func (o *ExternalSharingOptions) GetAnyoneInternalEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AnyoneInternalEnabled
}

func (o *ExternalSharingOptions) GetAnonymousAccessEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.AnonymousAccessEnabled
}

func (o *ExternalSharingOptions) GetUserAccessEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.UserAccessEnabled
}

func (o *ExternalSharingOptions) GetUserIds() []string {
	if o == nil {
		return nil
	}
	return o.UserIds
}

func (o *ExternalSharingOptions) GetDomainAccessEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.DomainAccessEnabled
}
