// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HotwordProximity struct {
	WindowBefore *int64 `json:"windowBefore,omitempty"`
	WindowAfter  *int64 `json:"windowAfter,omitempty"`
}

func (o *HotwordProximity) GetWindowBefore() *int64 {
	if o == nil {
		return nil
	}
	return o.WindowBefore
}

func (o *HotwordProximity) GetWindowAfter() *int64 {
	if o == nil {
		return nil
	}
	return o.WindowAfter
}
