// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MessageTextBlock struct {
	Text string      `json:"text"`
	Type ContentType `json:"type"`
}

func (o *MessageTextBlock) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *MessageTextBlock) GetType() ContentType {
	if o == nil {
		return ContentType("")
	}
	return o.Type
}

type Message struct {
	// The role of the message.
	Role *string `json:"role,omitempty"`
	// The content of the message.
	Content []MessageTextBlock `json:"content,omitempty"`
}

func (o *Message) GetRole() *string {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *Message) GetContent() []MessageTextBlock {
	if o == nil {
		return nil
	}
	return o.Content
}
