// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDocumentVisibilityOverridesRequest struct {
	VisibilityOverrides []DocumentVisibilityOverride `json:"visibilityOverrides,omitempty"`
}

func (o *UpdateDocumentVisibilityOverridesRequest) GetVisibilityOverrides() []DocumentVisibilityOverride {
	if o == nil {
		return nil
	}
	return o.VisibilityOverrides
}
