// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateDlpConfigResponse struct {
	Result *DlpSimpleResult `json:"result,omitempty"`
	// The id of the report that was just created and run.
	ReportID *string `json:"reportId,omitempty"`
}

func (o *UpdateDlpConfigResponse) GetResult() *DlpSimpleResult {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *UpdateDlpConfigResponse) GetReportID() *string {
	if o == nil {
		return nil
	}
	return o.ReportID
}
