// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

// WritePermission - Describes the write permissions levels that a user has for a specific feature
type WritePermission struct {
	// Describes the scope for a ReadPermission, WritePermission, or GrantPermission object
	ScopeType *ScopeType `json:"scopeType,omitempty"`
	// True if user has create permission for this feature and scope
	Create *bool `json:"create,omitempty"`
	// True if user has update permission for this feature and scope
	Update *bool `json:"update,omitempty"`
	// True if user has delete permission for this feature and scope
	Delete *bool `json:"delete,omitempty"`
}

func (w WritePermission) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WritePermission) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *WritePermission) GetScopeType() *ScopeType {
	if o == nil {
		return nil
	}
	return o.ScopeType
}

func (o *WritePermission) GetCreate() *bool {
	if o == nil {
		return nil
	}
	return o.Create
}

func (o *WritePermission) GetUpdate() *bool {
	if o == nil {
		return nil
	}
	return o.Update
}

func (o *WritePermission) GetDelete() *bool {
	if o == nil {
		return nil
	}
	return o.Delete
}
