// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/gleanwork/api-client-go/models/components"
)

type CollectionError struct {
	ErrorCode components.CollectionErrorErrorCode `json:"errorCode"`
	HTTPMeta  components.HTTPMetadata             `json:"-"`
}

var _ error = &CollectionError{}

func (e *CollectionError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
