// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DownloadreportcsvRequest struct {
	// The id of the report to download violations for.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DownloadreportcsvRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DownloadreportcsvResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Downloads csv of one-time report violations.
	Res *string
}

func (o *DownloadreportcsvResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DownloadreportcsvResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
