// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetchatapplicationRequest struct {
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset *int64                               `queryParam:"style=form,explode=true,name=timezoneOffset"`
	Body           components.GetChatApplicationRequest `request:"mediaType=application/json"`
}

func (o *GetchatapplicationRequest) GetTimezoneOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.TimezoneOffset
}

func (o *GetchatapplicationRequest) GetBody() components.GetChatApplicationRequest {
	if o == nil {
		return components.GetChatApplicationRequest{}
	}
	return o.Body
}

type GetchatapplicationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetChatApplicationResponse *components.GetChatApplicationResponse
}

func (o *GetchatapplicationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetchatapplicationResponse) GetGetChatApplicationResponse() *components.GetChatApplicationResponse {
	if o == nil {
		return nil
	}
	return o.GetChatApplicationResponse
}
