// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetreportstatusRequest struct {
	// The id of the report to get run status for.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetreportstatusRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetreportstatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Fetches status of report run.
	ReportStatusResponse *components.ReportStatusResponse
}

func (o *GetreportstatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetreportstatusResponse) GetReportStatusResponse() *components.ReportStatusResponse {
	if o == nil {
		return nil
	}
	return o.ReportStatusResponse
}
