// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type SearchAgentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	SearchAgentsResponse *components.SearchAgentsResponse
}

func (o *SearchAgentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SearchAgentsResponse) GetSearchAgentsResponse() *components.SearchAgentsResponse {
	if o == nil {
		return nil
	}
	return o.SearchAgentsResponse
}
